### ISSUE TITLE
`deno transpile --declaration` fails when compilerOptions.lib includes deno.ns

### ISSUE THREAD

**Issue by petamoriken** [denoland/deno#36709]
Version: Deno 2.9.6

`deno transpile --declaration` type-checking fails on Deno 2.9.6 with errors inside Deno's own `lib.deno.ns.d.ts`. The same command works on Deno 2.9.5. `deno check` and `deno transpile` without `--declaration` both succeed on 2.9.6.

This looks like `transpile --declaration` invokes tsc without `lib.node`, so the `import("node:net")` and `NodeJS.Timeout` references that `lib.deno.ns.d.ts` now uses cannot be resolved.

## Reproduction

```sh
echo 'export const x = 1;' > t.ts
deno transpile t.ts -o t.js --declaration
```

## Actual

```
error: Type checking failed:
TS2591 [ERROR]: Cannot find name 'node:net'.
    socket?: import("node:net").Socket;
                    ~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:5166:21

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
  export function refTimer(id: number | NodeJS.Timeout): void;
                                        ~~~~~~
    at asset:///lib.deno.ns.d.ts:5635:41

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
  export function unrefTimer(id: number | NodeJS.Timeout): void;
                                          ~~~~~~
    at asset:///lib.deno.ns.d.ts:5642:43

Found 3 errors.
```

No `.d.ts` is emitted.

## Expected

A `t.d.ts` is emitted, as on 2.9.5:

```ts
export declare const x = 1;
```

## What still works on 2.9.6

```sh
deno check t.ts                          # ok
deno transpile t.ts -o t.js              # ok (no --declaration)
```

`--no-check` does not help: `--declaration` still type-checks via tsc and fails with the same three errors.

Adding `"node"` / `"deno.ns"` to `compilerOptions.lib` also does not help:

```json
{ "compilerOptions": { "lib": ["dom", "dom.iterable", "esnext", "deno.ns", "node"] } }
```

```sh
deno transpile t.ts -o t.js --declaration --config deno.json
# same three errors
```

## Environment

```
deno 2.9.6 (stable, release, aarch64-apple-darwin)
v8 15.0.245.2-rusty
typescript 6.0.3
```

Also reproduced on GitHub Actions (`ubuntu-latest`, `denoland/setup-deno@v2` with `deno-version: latest`). Last known good: Deno 2.9.5.

**Comment by bartlomieju** [comment]
Thanks for the detailed report. I haven't been able to reproduce this from the
steps given, but I did find a closely related divergence — details below, plus a
couple of questions.

## Not reproducing as written

Running your exact repro on `2.9.6` (`aarch64-apple-darwin`, `typescript 6.0.3`)
and on current `main`:

```
$ echo 'export const x = 1;' > t.ts
$ deno transpile t.ts -o t.js --declaration
Emit .../t.js
Emit .../t.d.ts
```

Both emit `t.d.ts` with no diagnostics. I also tried an empty `deno.json`, a
`package.json` in the directory, `"nodeModulesDir": "auto"`, and a cold
`DENO_DIR` — none reproduce the `node:net` / `NodeJS` errors.

Your line numbers do check out against the `v2.9.6` tag exactly
(`lib.deno.ns.d.ts:5166`, `:5635`, `:5642`), so this isn't a version mismatch —
something environmental is differing between our setups.

## A related bug that does reproduce

With an explicit `compilerOptions.lib`, `check` and `transpile --declaration`
disagree on identical input, on both 2.9.6 and `main`:

```jsonc
// deno.json
{ "compilerOptions": { "lib": ["dom", "dom.iterable", "esnext", "deno.ns", "node"] } }
```

```
$ deno check t.ts
Check t.ts                                    # passes

$ deno transpile t.ts -o t.js --declaration
error: Type checking failed:
TS2724 [ERROR]: 'globalThis' has no exported member named 'TransformerCancelCallback'.
    type TransformerCancelCallback = globalThis.TransformerCancelCallback;
    at asset:///node/stream/web.d.cts:59:49
```

Different diagnostics from yours, but the same underlying thesis: the declaration
pass builds a different program than `check` does. Two concrete gaps:

1. `cli/tools/transpile.rs` builds its module graph via
   `build_graph_roots_with_npm_resolution` with no `imports`, whereas
   `cli/tools/check.rs` passes `maybe_resolve_ts_config_imports(...)`. So
   `compilerOptions.types` never reaches the graph.
2. `TypeChecker::emit_declarations` passes `root_names` through untouched, while
   the check path first runs them through `GraphWalker::add_config_import`
   before `into_tsc_roots()`. So those types never become tsc program roots.

On `main` there's a third, larger factor: `check` now runs through the native
TypeScript compiler while `transpile --declaration` still uses the in-process JS
tsc, and the two compose the lib set differently.

## Questions

To pin down your case specifically:

- Do you have a `deno.json` / `deno.jsonc` in the project (or any parent
  directory), and if so what's in `compilerOptions`? The bare repro in the issue
  implies none, but the errors look like a program built without the node types.
- Is there a `package.json` or `node_modules` in scope?
- Does `deno transpile t.ts -o t.js --declaration -q --reload` in a fresh empty
  directory still fail for you?
- Could you share the output of `deno check --log-level=debug t.ts` alongside the
  failing transpile invocation?

If you have a repo or GitHub Actions run that shows the failure, that would be
the fastest path.

**Comment by petamoriken** [comment]
@bartlomieju Thank you for checking this out!

> If you have a repo or GitHub Actions run that shows the failure, that would be the fastest path.

Here are the repository and the GitHub Actions logs:

https://github.com/petamoriken/PxtoneJS
https://github.com/petamoriken/PxtoneJS/actions/runs/33099793861/job/98614120056

---

> * Do you have a `deno.json` / `deno.jsonc` in the project (or any parent directory), and if so what's in `compilerOptions`? The bare repro in the issue implies none, but the errors look like a program built without the node types.

Here is the configuration:

```
"compilerOptions": {
  "lib": ["dom", "dom.iterable", "deno.ns"]
}
```

> * Is there a `package.json` or `node_modules` in scope?

There is no `package.json`, but `node_modules` exists.

> * Does `deno transpile t.ts -o t.js --declaration -q --reload` in a fresh empty directory still fail for you?

It did not occur in an empty directory. It seems to be an error specific to this project.

> * Could you share the output of `deno check --log-level=debug t.ts` alongside the failing transpile invocation?

Here it is:

<details>
<summary><code>deno check --log-level=debug t.ts</code></summary>

```
DEBUG RS - deno_config::deno_json:1778 - Config file found at '/Users/moriken/Developer/PxtoneJS/deno.json'
DEBUG RS - deno::args:600 - Finished config loading.
DEBUG RS - deno::cache::cache_db:204 - Opening cache /Users/moriken/Library/Caches/deno/dep_analysis_cache_v2...
DEBUG RS - deno::cache::cache_db:204 - Opening cache /Users/moriken/Library/Caches/deno/node_analysis_cache_v2...
DEBUG RS - deno::cache::cache_db:204 - Opening cache /Users/moriken/Library/Caches/deno/fast_check_cache_v2...
DEBUG RS - deno::cache::cache_db:204 - Opening cache /Users/moriken/Library/Caches/deno/check_cache_v2...
DEBUG RS - deno::cache::cache_db:204 - Opening cache /Users/moriken/Library/Caches/deno/v8_code_cache_v2...
DEBUG RS - deno_resolver::npmrc:125 - .npmrc found at: '/Users/moriken/.npmrc'
DEBUG RS - deno_resolver::npmrc:251 - Only home .npmrc file found
DEBUG RS - deno_resolver::factory:1036 - Newest dependency date: 2026-08-26 00:19:48.595332 UTC
DEBUG RS - deno_resolver::workspace:1112 - Workspace config generated this import map {
  "imports": {
    "@deno/dnt": "jsr:@deno/dnt@^0.43.2",
    "@deno/dnt/": "jsr:/@deno/dnt@^0.43.2/",
    "@std/assert": "jsr:@std/assert@^1.0.19",
    "@std/assert/": "jsr:/@std/assert@^1.0.19/",
    "@std/toml": "jsr:@std/toml@^1.0.11",
    "@std/toml/": "jsr:/@std/toml@^1.0.11/",
    "vite": "npm:vite@^8.2.2",
    "vite/": "npm:/vite@^8.2.2/"
  }
}
DEBUG RS - deno::module_loader:197 - Preparing module load.
DEBUG RS - deno::module_loader:243 - Building module graph.
DEBUG RS - deno_npm_installer:511 - All package.json deps resolvable. Skipping top level install.
DEBUG RS - deno_cache_dir::file_fetcher:638 - FileFetcher::fetch_no_follow - specifier: file:///Users/moriken/Developer/PxtoneJS/t.ts
DEBUG RS - deno::type_checker:314 - Type checking
DEBUG RS - deno::graph_util:1142 - Building fast check graph
Check t.ts
DEBUG RS - deno::tsc:919 - exec request, root_names: [("file:///Users/moriken/Developer/PxtoneJS/t.ts", TypeScript)]
DEBUG RS - deno::tsc::js:443 - V8 code cache hit for Extension module: ext:deno_cli_tsc/99_main_compiler.js, [14805535795879793003]
DEBUG RS - deno::tsc::js:443 - V8 code cache hit for Extension module: ext:deno_cli_tsc/97_ts_host.js, [11421532499208713503]
DEBUG RS - deno::tsc::js:443 - V8 code cache hit for Extension module: ext:deno_cli_tsc/98_lsp.js, [17495958233431078757]
DEBUG RS - deno::tsc::js:443 - V8 code cache hit for Extension module: ext:deno_cli_tsc/00_typescript.js, [8526734423526244216]
DEBUG TS - >>> exec start {"rootNames":["file:///Users/moriken/Developer/PxtoneJS/t.ts"]}
DEBUG TS - {"allowJs":true,"allowImportingTsExtensions":true,"allowSyntheticDefaultImports":true,"checkJs":false,"emitDecoratorMetadata":false,"experimentalDecorators":false,"incremental":true,"jsx":"react","importsNotUsedAsValues":"remove","inlineSourceMap":true,"inlineSources":true,"isolatedModules":true,"lib":["dom","dom.iterable","deno.ns"],"module":"NodeNext","moduleDetection":"force","noEmit":true,"noImplicitOverride":true,"resolveJsonModule":true,"sourceMap":false,"skipLibCheck":false,"strict":true,"target":"esnext","tsBuildInfoFile":"internal:///.tsbuildinfo","useDefineForClassFields":true}
DEBUG TS - host.readFile("internal:///.tsbuildinfo")
DEBUG TS - host.getCurrentDirectory()
DEBUG TS - host.fileExists("file:///Users/moriken/Developer/PxtoneJS/package.json")
DEBUG TS - host.fileExists("file:///Users/moriken/Developer/package.json")
DEBUG TS - host.fileExists("file:///Users/moriken/package.json")
DEBUG TS - host.fileExists("file:///Users/package.json")
DEBUG TS - host.fileExists("file:///package.json")
DEBUG TS - host.getSourceFile("file:///Users/moriken/Developer/PxtoneJS/t.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.dom.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es5.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.decorators.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.decorators.legacy.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.core.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.collection.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.iterable.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.symbol.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.generator.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.proxy.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.reflect.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2015.symbol.wellknown.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.asynciterable.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.dom.iterable.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.deno.ns.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2023.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2021.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2016.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2016.array.include.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2016.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.arraybuffer.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.date.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.object.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.sharedmemory.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2017.typedarrays.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.asyncgenerator.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.regexp.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2018.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.array.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.object.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.symbol.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2019.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.bigint.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.date.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.number.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.sharedmemory.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2020.symbol.wellknown.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2021.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2021.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2021.weakref.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2021.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.array.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.error.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.object.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.regexp.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2022.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2023.array.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2023.collection.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2023.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.arraybuffer.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.collection.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.object.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.regexp.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.sharedmemory.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2024.string.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.collection.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.float16.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.iterator.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.promise.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.es2025.regexp.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.intl.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.temporal.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.collection.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.decorators.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.disposable.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.array.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.error.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.sharedmemory.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.typedarrays.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.esnext.date.d.ts", Latest)
DEBUG TS - host.fileExists("asset:///package.json")
DEBUG TS - host.getSourceFile("asset:///lib.deno.net.d.ts", Latest)
DEBUG TS - host.resolveModuleNames()
DEBUG TS -   base: asset:///lib.deno.ns.d.ts
DEBUG TS -   specifiers: node:net
DEBUG TS - host.getSourceFile("node:net", Latest)
DEBUG TS - host.writeFile("internal:///.tsbuildinfo")
DEBUG TS - <<< exec stop
DEBUG RS - deno::type_checker:689 - Ambient Modules: []
DEBUG RS - deno::type_checker:731 - Compilation statistics:
  Files: 92
  Nodes: 153515
  Identifiers: 54229
  Symbols: 34640
  Types: 88
  Instantiations: 0
  Parse time: 94
  Bind time: 29
  Check time: 2
  Emit time: 1
  Total TS time: 126
  Compile time: 133

DEBUG RS - deno::module_loader:288 - Prepared module load.
```

</details>

**Comment by petamoriken** [comment]
# AI Investigation

Update after more isolation: this is **not** broken for every project on 2.9.6. It only fails when `compilerOptions.lib` includes `deno.ns` (and `--declaration` is used).

This project's `deno.json` has:

```json
{ "compilerOptions": { "lib": ["dom", "dom.iterable", "deno.ns"] } }
```

That combination is the documented way to get DOM types and `Deno.*` in the same program. `deno check` still succeeds with it. `deno transpile --declaration` does not.

## Isolated matrix (Deno 2.9.6)

| `compilerOptions.lib` | `transpile --declaration` |
| --- | --- |
| *(default / no deno.json)* | OK |
| `["deno.window"]` | OK |
| `["dom", "dom.iterable"]` | OK |
| `["dom", "dom.iterable", "esnext"]` | OK |
| `["deno.ns"]` | FAIL |
| `["deno.ns", "node"]` | FAIL |
| `["dom", "dom.iterable", "deno.ns"]` | FAIL |
| `["dom", "dom.iterable", "deno.ns", "node"]` | FAIL |
| `["esnext", "deno.ns"]` | FAIL |
| `["node"]` | FAIL |

`--no-config` does **not** avoid the failure if a `deno.json` with `deno.ns` in `lib` is in the cwd (or a parent). `--config` pointing at a DOM-only override also does not help while that cwd config is still visible. Starting the same command from a directory whose `deno.json` does not include `deno.ns` succeeds.

Sorry for the earlier “any file fails” framing — that was because the original repros were run from a repo whose `deno.json` already had this `lib`.
