### ISSUE TITLE
Post install script fails in Deno 2.0.5

### ISSUE THREAD

**Issue by irbull** [denoland/deno#26765]
Version: Deno 2.0.5

This worked in Deno 2.0.4.

Create a `package.json` with the following content:
```json
{
  "dependencies": {
    "sharp": "^0.33.5"
  }
}
```
Run the following:
1. `rm -rf node_modules` (make sure there is no existing `node_modules` folder)
2. `deno install -r --allow-scripts=npm:sharp@0.33.5,npm:@swc/core@1.9.1`
3. Fails with:
```
error: script 'install' in 'sharp@0.33.5' failed with exit code 1
stderr:
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/irbull/git/deno/2.0.5-bug/node_modules/.deno/sharp@0.33.5/node_modules/sharp/install/check' imported from 'file:///Users/irbull/git/deno/2.0.5-bug/node_modules/.deno/sharp@0.33.5/node_modules/sharp'
```

If I run this command a second time, it works. 

This fail on Mac and in my GitHub CI Jobs (Linux).
