### ISSUE TITLE
remote CDN imports not being properly resolved

### ISSUE THREAD

**Issue by FredKSchott** [denoland/deno#4117]
Originally reported here: https://github.com/gcanti/fp-ts/issues/1130
Confirmed regression locally, working on v0.33.0 but broken on v0.34.0
Can't seem to import anything from the Pika CDN due to this.

For context, every package (ex: https://cdn.pika.dev/fp-ts@^2.4.4) will always import from another file by `/*` path.

```
$ cat test.ts
import * as ns from 'https://cdn.pika.dev/fp-ts@^2.4.4';
console.log(ns);

$ deno --reload test.ts
Compile file:///test/test.ts
Download https://cdn.pika.dev/fp-ts@^2.4.4

error TS2307: Cannot find module '/-/fp-ts@v2.5.1-bEgPQP5yi6MRzC5XlNqk/dist=es2019/fp-ts.js'.
► http://localhost:3005/fp-ts@^2.4.4:23:15
23 export * from '/-/fp-ts@v2.5.1-bEgPQP5yi6MRzC5XlNqk/dist=es2019/fp-ts.js';
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error TS2307: Cannot find module '/-/fp-ts@v2.5.1-bEgPQP5yi6MRzC5XlNqk/dist=es2019/fp-ts.js'.
► http://localhost:3005/fp-ts@^2.4.4:24:23
24 export {default} from '/-/fp-ts@v2.5.1-bEgPQP5yi6MRzC5XlNqk/dist=es2019/fp-ts.js';
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors.
```

**Comment by kitsonk** [comment]
Hrmmmm... yeah, it was all in the same domain space of trying to "improve" import detection problems on some modules (ref: #4040 #4010 #4110 #4078)

The use cases help, just need to figure out how to make everyone happy.

**Comment by FredKSchott** [comment]
👍 sounds like you're on top of it. Let me know if I can help in any way!
