### ISSUE TITLE
error LNK2019: unresolved external symbol 

### ISSUE THREAD

**Issue by aliabolhassani** [denoland/deno#3716]
Linker gives error: linking with `link.exe` failed: exit code: 1120 with the following details:
|
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" ...

  = note: libdeno_core-bdc8737d05bc28a0.rlib(deno_core-bdc8737d05bc28a0.3vq8sopdlcddeykw.rcgu.o) : error LNK2019: unresolved external symbol _v8__Local__New referenced in function __ZN8rusty_v86global15Global$LT$T$GT$3get28_$u7b$$u7b$closure$u7d$$u7d$17h05d8f060dc1b5cb7E

**Comment by ry** [comment]
Maybe do "cargo clean" and try again?

**Comment by aliabolhassani** [comment]
It didn't work. Tried a clean clone on another Win10 VM using the latest Python2, Rust and MSVS2017 leading to the same result. Find the full terminal output here: [terminal.txt](https://github.com/denoland/deno/files/4083766/terminal.txt)

I was wondering if anyone else has the same issue on VMs?

**Comment by seishun** [comment]
It seems this particular problem was introduced in 5f1df038fb1462607af3555fa7431c05ca484dce. However, the previous commit doesn't build either and fails with other unresolved external symbols, e.g. _deno_delete and _deno_new. @aliabolhassani is it the same for you?

**Comment by aliabolhassani** [comment]
@seishun I created the issue for [`c50cab9`](https://github.com/denoland/deno/commit/c50cab90a05d271013f741768d70c1eda6ef9a10). However, I tried the latest one i.e, [`7d115a2`](https://github.com/denoland/deno/commit/7d115a2a657fcfc54670e56cad3fe44fc7a59a9f) with the same results on virtual/actual Windows machines. But, [`23e67eb`](https://github.com/denoland/deno/commit/23e67eb5153bd26dbae471b27dc6a21a6d283b0b) works fine on my MacBook.

**Comment by seishun** [comment]
The solution is to uninstall Rust and install the 64-bit toolchain (https://github.com/denoland/rusty_v8/issues/269#issuecomment-583791122). I suppose this should be documented.

**Comment by aliabolhassani** [comment]
Thank you @seishun. It worked.
