### ISSUE TITLE
Bundler throws TS errors that running the script doesn't 

### ISSUE THREAD

**Issue by nekdolan** [denoland/deno#8218]
I use a dependency from npm and when I try to bundle my script instead of running it it is throwing errors and won't compile.

Errors
```
error: TS2552 [ERROR]: Cannot find name 'global'. Did you mean '_global'?
var _global = typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : global;
                                                                                                    ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:1:101

    '_global' is declared here.
    var _global = typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : global;
        ~~~~~~~
        at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:1:5

TS2441 [ERROR]: Duplicate identifier 'exports'. Compiler reserves name 'exports' in top level scope of a module.
var exports = {};
    ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:3:5

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      (this || _global).data = data;
                        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:12:25

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      (this || _global).length = (this || _global).data.length;
                        ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:13:25

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      (this || _global).length = (this || _global).data.length;
                                                   ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:13:52

TS2339 [ERROR]: Property 'compare' does not exist on type 'TinyQueue'.
      (this || _global).compare = compare;
                        ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:14:25

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      if ((this || _global).length > 0) {
                            ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:16:29

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
        for (let i = ((this || _global).length >> 1) - 1; i >= 0; i--) this._down(i);
                                        ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:17:41

TS7006 [ERROR]: Parameter 'item' implicitly has an 'any' type.
    push(item) {
         ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:21:10

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      (this || _global).data.push(item);
                        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:22:25

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      (this || _global).length++;
                        ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:24:25

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      this._up((this || _global).length - 1);
                                 ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:26:34

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      if ((this || _global).length === 0) return undefined;
                            ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:30:29

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      const top = (this || _global).data[0];
                                    ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:31:37

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      (this || _global).length--;
                        ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:32:25

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      if ((this || _global).length > 0) {
                            ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:34:29

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
        (this || _global).data[0] = (this || _global).data[(this || _global).length];
                          ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:35:27

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
        (this || _global).data[0] = (this || _global).data[(this || _global).length];
                                                      ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:35:55

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
        (this || _global).data[0] = (this || _global).data[(this || _global).length];
                                                                             ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:35:78

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      (this || _global).data.pop();
                        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:40:25

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
      return (this || _global).data[0];
                               ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:46:32

TS7006 [ERROR]: Parameter 'pos' implicitly has an 'any' type.
    _up(pos) {
        ~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:49:9

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
        data,
        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:51:9

TS2339 [ERROR]: Property 'compare' does not exist on type 'TinyQueue'.
        compare
        ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:52:9

TS7006 [ERROR]: Parameter 'pos' implicitly has an 'any' type.
    _down(pos) {
          ~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:67:11

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
        data,
        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:69:9

TS2339 [ERROR]: Property 'compare' does not exist on type 'TinyQueue'.
        compare
        ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:70:9

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
      const halfLength = (this || _global).length >> 1;
                                           ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:72:44

TS2339 [ERROR]: Property 'length' does not exist on type 'TinyQueue'.
        if (right < (this || _global).length && compare(data[right], best) < 0) {
                                      ~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:80:39

TS7006 [ERROR]: Parameter 'a' implicitly has an 'any' type.
  function defaultCompare(a, b) {
                          ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:95:27

TS7006 [ERROR]: Parameter 'b' implicitly has an 'any' type.
  function defaultCompare(a, b) {
                             ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:95:30

TS7006 [ERROR]: Parameter 'e1' implicitly has an 'any' type.
  function checkWhichEventIsLeft(e1, e2) {
                                 ~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:99:34

TS7006 [ERROR]: Parameter 'e2' implicitly has an 'any' type.
  function checkWhichEventIsLeft(e1, e2) {
                                     ~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:99:38

TS7006 [ERROR]: Parameter 'seg1' implicitly has an 'any' type.
  function checkWhichSegmentHasRightEndpointFirst(seg1, seg2) {
                                                  ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:106:51

TS7006 [ERROR]: Parameter 'seg2' implicitly has an 'any' type.
  function checkWhichSegmentHasRightEndpointFirst(seg1, seg2) {
                                                        ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:106:57

TS7006 [ERROR]: Parameter 'p' implicitly has an 'any' type.
    constructor(p) {
                ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:114:17

TS2339 [ERROR]: Property 'p' does not exist on type 'Event'.
      (this || _global).p = {
                        ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:115:25

TS2339 [ERROR]: Property 'otherEvent' does not exist on type 'Event'.
      (this || _global).otherEvent = null;
                        ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:119:25

TS2339 [ERROR]: Property 'isLeftEndpoint' does not exist on type 'Event'.
      (this || _global).isLeftEndpoint = null;
                        ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:120:25

TS7006 [ERROR]: Parameter 'eventToCheck' implicitly has an 'any' type.
    isSamePoint(eventToCheck) {
                ~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:123:17

TS2339 [ERROR]: Property 'p' does not exist on type 'Event'.
      return (this || _global).p.x === eventToCheck.p.x && (this || _global).p.y === eventToCheck.p.y;
                               ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:124:32

TS2339 [ERROR]: Property 'p' does not exist on type 'Event'.
      return (this || _global).p.x === eventToCheck.p.x && (this || _global).p.y === eventToCheck.p.y;
                                                                             ^
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:124:78

TS7006 [ERROR]: Parameter 'geojson' implicitly has an 'any' type.
  function fillEventQueue(geojson, eventQueue) {
                          ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:129:27

TS7006 [ERROR]: Parameter 'eventQueue' implicitly has an 'any' type.
  function fillEventQueue(geojson, eventQueue) {
                                   ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:129:36

TS7006 [ERROR]: Parameter 'featureOrGeometry' implicitly has an 'any' type.
  function processFeature(featureOrGeometry, eventQueue) {
                          ~~~~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:141:27

TS7006 [ERROR]: Parameter 'eventQueue' implicitly has an 'any' type.
  function processFeature(featureOrGeometry, eventQueue) {
                                             ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:141:46

TS2339 [ERROR]: Property 'otherEvent' does not exist on type 'Event'.
          e1.otherEvent = e2;
             ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:157:14

TS2339 [ERROR]: Property 'otherEvent' does not exist on type 'Event'.
          e2.otherEvent = e1;
             ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:158:14

TS2339 [ERROR]: Property 'isLeftEndpoint' does not exist on type 'Event'.
            e2.isLeftEndpoint = true;
               ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:161:16

TS2339 [ERROR]: Property 'isLeftEndpoint' does not exist on type 'Event'.
            e1.isLeftEndpoint = false;
               ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:162:16

TS2339 [ERROR]: Property 'isLeftEndpoint' does not exist on type 'Event'.
            e1.isLeftEndpoint = true;
               ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:164:16

TS2339 [ERROR]: Property 'isLeftEndpoint' does not exist on type 'Event'.
            e2.isLeftEndpoint = false;
               ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:165:16

TS7006 [ERROR]: Parameter 'event' implicitly has an 'any' type.
    constructor(event) {
                ~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:177:17

TS2339 [ERROR]: Property 'leftSweepEvent' does not exist on type 'Segment'.
      (this || _global).leftSweepEvent = event;
                        ~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:178:25

TS2339 [ERROR]: Property 'rightSweepEvent' does not exist on type 'Segment'.
      (this || _global).rightSweepEvent = event.otherEvent;
                        ~~~~~~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:179:25

TS7006 [ERROR]: Parameter 'seg1' implicitly has an 'any' type.
  function testSegmentIntersect(seg1, seg2) {
                                ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:184:33

TS7006 [ERROR]: Parameter 'seg2' implicitly has an 'any' type.
  function testSegmentIntersect(seg1, seg2) {
                                      ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:184:39

TS7006 [ERROR]: Parameter 'eventQueue' implicitly has an 'any' type.
  function runCheck(eventQueue) {
                    ~~~~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:217:21

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
        for (let i = 0; i < outQueue.data.length; i++) {
                                     ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:228:38

TS2339 [ERROR]: Property 'data' does not exist on type 'TinyQueue'.
          const intersection = testSegmentIntersect(segment, outQueue.data[i]);
                                                                      ~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:229:71

TS7006 [ERROR]: Parameter 'geojson' implicitly has an 'any' type.
  function sweeplineIntersections(geojson) {
                                  ~~~~~~~
    at https://jspm.dev/npm:sweepline-intersections@1.1.2!cjs:243:35

Found 61 errors.
```

**Comment by nekdolan** [comment]
Works in 1.5.1 closing
