### PR TITLE
fix(ext/node): support fs ops on inherited extra stdio fds

### LINKED ISSUE #33368: `node:child_process`: fd 3 pipe broken in spawn()
Version: Deno 2.7.12

Hi,

I would like to report a behavior in Deno that can be reproduced using the below PoC:

1. index.mjs
```javascript
import { spawn } from 'node:child_process';

const child = spawn(process.execPath, ['src/child.mjs'], {
  stdio: ['inherit', 'inherit', 'inherit', 'pipe']
});

console.log(`${child.stdio.length} available file descriptors`);

// Attach listener to the extra fd (index 3)
child.stdio[3].on('data', (d) => {
  console.log(`fd 3: ${d.toString()}`);
});

child.on('exit', (code, signal) => {
  console.log(`child exited with code=${code} signal=${signal}`);
});
```
2. child.mjs
```javascript
import { createWriteStream } from 'node:fs';

// Child process: write to extra file descriptor 3
const stdio3 = createWriteStream(null, { fd: 3 });
console.log('stdout: createWriteStream fd: 3');

// This write should be observable by the parent on child.stdio[3]
stdio3.write('hi from child! using fd 3');
```

### Expected output
```
root@KContainer:~/11044# node src/index.mjs
4 available file descriptors
stdout: createWriteStream fd: 3
fd 3: hi from child! using fd 3
child exited with code=0 signal=null

```

### Actual output
Throws bad file descriptor error
```
root@KContainer:~/11044# deno run -A src/index.mjs
4 available file descriptors
stdout: createWriteStream fd: 3
error: Uncaught Error: Bad file descriptor (os error 9)
    at Timeout._onTimeout (node:fs:637:7)
    at Object.cb [as _onTimeout] (ext:deno_node/internal/timers.mjs:149:16)
    at listOnTimeout (ext:core/02_timers.js:307:17)
    at Object.processTimers (ext:core/02_timers.js:250:7)
    at __eventLoopTick (ext:core/01_core.js:461:33)
child exited with code=1 signal=null
```

### PR DESCRIPTION
**Pull request by bartlomieju**
## Summary

Closes #33368

`fs.write(fd)` / `fs.read(fd)` and other node:fs ops go through `file_for_fd()` which looks up the fd in `FdTable`. File descriptors inherited from a parent process via `child_process.spawn({ stdio: [..., 'pipe'] })` are valid OS fds but were never registered in the table, causing EBADF.

This was introduced in #33165 (2.7.12) when `file_for_fd` was changed to use `FdTable` instead of the old resource-table-based lookup.

When an fd is not in `FdTable`, `file_for_fd` now validates it against the OS and wraps it via `dup()` on Unix / `DuplicateHandle` on Windows, so the operation succeeds without closing the original fd on drop.

## Test plan
- Added spec test `child_process_extra_pipe_fd` — spawns a child with `stdio: ['inherit', 'inherit', 'inherit', 'pipe']`, child writes to fd 3 via `fs.createWriteStream(null, { fd: 3 })`, parent reads from `child.stdio[3]`
- Verified the original repro from #33368 now works

### CODE REVIEW

File: ext/node/ops/fs.rs [hunk 1]
```diff
@@ -98,15 +98,69 @@ fn ebadf() -> FsError {
 }
 
 /// Get the File trait object for an OS file descriptor from FdTable.
+///
+/// If the fd is not in the table (e.g. an inherited pipe from
+/// `child_process.spawn`), validates and wraps the raw OS fd so that
+/// `fs.write(fd)` / `fs.read(fd)` work on any open descriptor.
 fn file_for_fd(
```
Comment (bartlomieju) [inline ext/node/ops/fs.rs:105]: Meh, this is not a correct solution... I think on startup we should either forward which FDs are pipes from parent proces (via env var) or iterate over FDs for the process on startup.

**Review by fibibot — COMMENTED** [review]
Substance is right and addresses a real regression introduced by #33165 (the `file_for_fd` switch from resource-table to `FdTable`-based lookup, which broke any inherited fd that was never registered). The fix's design is sound: when an fd isn't in `FdTable`, validate it against the OS and wrap via `dup()` on Unix / `DuplicateHandle` on Windows so the operation succeeds without closing the original on drop. The new spec test (`tests/specs/node/child_process_extra_pipe_fd/`) directly exercises the #33368 repro shape (`stdio: ['inherit', 'inherit', 'inherit', 'pipe']` + child writes via `fs.createWriteStream(null, { fd: 3 })`).

## Blocker — Windows build break

The Windows `wrap_raw_fd` path (`ext/node/ops/fs.rs:148+`) doesn't compile on the current `windows-sys` version on main. CI shows the same compile error on `build debug windows-x86_64` and `build debug windows-aarch64` (and the dependent `lint debug windows-x86_64` shard rolls it up):

```
error[E0308]: arguments to this function are incorrect
   --> ext\node\ops\fs.rs:148:5
148 |     DuplicateHandle(
    |     ^^^^^^^^^^^^^^^
note: expected `*mut c_void`, found `isize`
   --> ext\node\ops\fs.rs:150:7
150 |       handle,
    |       ^^^^^^
note: expected `*mut *mut c_void`, found `&mut isize`
   --> ext\node\ops\fs.rs:152:7
152 |       &mut new_handle,
```

In `windows-sys 0.59` the `HANDLE` type changed from `isize` to `*mut c_void`. The PR was apparently written against a pre-0.59 windows-sys (PR is from 2026-04-22, ~12 days old). Two-line fix:

```rust
use windows_sys::Win32::Foundation::HANDLE;

let handle: HANDLE = unsafe { libc::get_osfhandle(fd) } as HANDLE;
if handle.is_null() {
  return Err(ebadf());
}
let mut new_handle: HANDLE = std::ptr::null_mut();
let ok = unsafe {
  DuplicateHandle(
    GetCurrentProcess(),
    handle,
    GetCurrentProcess(),
    &mut new_handle,
    0,
    0,
    DUPLICATE_SAME_ACCESS,
  )
};
```

Also adjust the `if handle == -1` check — `libc::get_osfhandle` returns `intptr_t` (`isize`) where `-1` (now `INVALID_HANDLE_VALUE` after the cast) signals error. Either keep the check pre-cast (`if handle_isize == -1`) or cast and check `if handle == INVALID_HANDLE_VALUE`.

The `from_raw_handle(new_handle as _)` line at the bottom should already work since `as _` infers the right target type.

## Smaller observations (non-blocking)

- **`ok == 0` short-circuit** correctly maps Windows BOOL=0 (FALSE) to error. ✓
- **Test's parent.ts uses `child.stdio[3]`** — this assumes `stdio[3]` is exposed, which Node does. Worth verifying Deno's `child_process` polyfill currently surfaces extra stdio fds via `child.stdio[N]` (the test would have failed manually if not, so presumably fine).
- **Stale**: PR is 12 days old, so the Windows-sys break may have happened after the PR was opened. A rebase + the type-fix above should clear all 6 failed shards (the 2 windows builds are the root failures; the 2 lint shards roll those up; the macos lint cancellation is downstream auto-cancel; the linux-x86_64 release `node_compat` failure is... probably unrelated, worth confirming on a re-run).

With the windows-sys-0.59 type adjustment this is APPROVE-shape — substance addresses the regression cleanly.

**Review by lunadogbot — CHANGES_REQUESTED** [review]
Requesting changes because the Windows path does not compile on the current `windows-sys`: `DuplicateHandle(..., handle, ..., &mut new_handle, ...)` passes `isize` values, but the API expects `HANDLE` / `*mut c_void` pointers. The current main helper `raw_fd_from_backing_fd` already uses `std::ptr::null_mut()` plus `handle_fd as _`; rebase and use that shape, or keep the `_get_osfhandle` `-1` check before casting and make `handle` / `new_handle` pointer-typed.

CI is red for `build debug windows-x86_64` and `build debug windows-aarch64`, and those failures come from this code path.

**Comment by bartlomieju** [comment]
Closing in favor of #34133, which fixes the same issue (#33368) with a properly scoped approach.

This PR fixes the EBADF by having `file_for_fd` fall back to wrapping *any* valid raw OS descriptor. Unfortunately that removes the only gate on node:fs fd operations: a script without `--allow-read`/`--allow-write` could then scan fd numbers and read/write descriptors Deno opened internally (module-cache sqlite, deno.lock, KV, etc.), which is a permission escape rather than just a compat fix.

#34133 instead registers only the specific inherited stdio fds that Deno's own spawn path created (communicated via an env var, dup'd once at startup, env var consumed so it doesn't leak to grandchildren), preserving the permission boundary and additionally handling the net.Socket({ fd }) reclaim path that fork/cluster need.
