### ISSUE TITLE
deno 1.27.1 fails to build with rust 1.65.0

### ISSUE THREAD

**Issue by ht990332** [denoland/deno#16540]
```
   Compiling test_util v0.1.0 (/home/hussam/cache/system/deno/src/deno/test_util)
error[E0277]: the trait bound `LiteralDef: std::cmp::Eq` is not satisfied
   --> /home/hussam/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_doc-0.48.0/src/ts_type.rs:980:3
    |
969 | #[derive(Debug, Default, Serialize, Deserialize, Clone, PartialEq, Eq)]
    |                                                                    -- in this derive macro expansion
...
980 |   pub literal: Option<LiteralDef>,
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `LiteralDef`
    |
    = help: the trait `std::cmp::Eq` is implemented for `std::option::Option<T>`
    = note: required for `std::option::Option<LiteralDef>` to implement `std::cmp::Eq`
note: required by a bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `deno_doc` due to previous error
```

**Comment by janschiefer** [comment]
I have a sililiar isse when building deno 1.27.1 with rustc 1.67.0-nightly (95a3a7277 2022-10-31).

`
(...)
  Compiling deno_graph v0.37.1
   Compiling dprint-plugin-typescript v0.76.0
   Compiling deno_doc v0.48.0
   Compiling eszip v0.29.0
   Compiling deno_emit v0.10.0
error[E0277]: the trait bound `LiteralDef: std::cmp::Eq` is not satisfied
   --> /home/jschiefer/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_doc-0.48.0/src/ts_type.rs:980:3
    |
969 | #[derive(Debug, Default, Serialize, Deserialize, Clone, PartialEq, Eq)]
    |                                                                    -- in this derive macro expansion
...
980 |   pub literal: Option<LiteralDef>,
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `LiteralDef`
    |
    = help: the trait `std::cmp::Eq` is implemented for `std::option::Option<T>`
    = note: required for `std::option::Option<LiteralDef>` to implement `std::cmp::Eq`
note: required by a bound in `AssertParamIsEq`
   --> /home/jschiefer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:313:31
    |
313 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `deno_doc` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.27.1`, intermediate artifacts can be found at `/tmp/cargo-installYhCsRc`
`

**Comment by bartlomieju** [comment]
This will be fixed in coming days, we need to update our internal `deno_*` crates, however some of the Rust tooling is not yet available for M1 mac and I can't fix it beforehand.
