### ISSUE TITLE
deno test - default test file pattern no longer works (regression)

### ISSUE THREAD

**Issue by MirKml** [denoland/deno#24594]
Version: Deno 1.45.2

After upgrade deno from 1.44.4 to 1.45.2 `deno test` default pattern no longer works - as is mentioned in [docs](https://docs.deno.com/runtime/manual/basics/testing/#running-tests).
Now - 1.45.2 it matches everything in particular directory

```
$  deno test --allow-read=__tests__ --allow-write=__tests__ __tests__
Check file:///E:/<fullpath>/__tests__/env-template.ts
Check file:///E:/<fullpath>/__tests__/mockServerLocalConvert_test.ts
Check file:///E:/<fullpath>/__tests__/mockServerLocalResult.js
Check file:///E:/<fullpath>/__tests__/setOptions_test.ts
error: TS2339 [ERROR]: Property 'createEnvConfig' does not exist on type 'Window & typeof globalThis'.
```

with old 1.44.4
```
$  deno test --allow-read=__tests__ --allow-write=__tests__ __tests__
running 1 test from ./__tests__/mockServerLocalConvert_test.ts
mock server local convert test ... ok (7ms)
running 1 test from ./__tests__/setOptions_test.ts
setOptionsByMockServer test ... ok (0ms)

ok | 2 passed | 0 failed (41ms)
```

There is also change in presented path - original was relative, now is full path. I'm in favor of relative - as presented in cli parametr and it's more readable

**Comment by MirKml** [comment]
hmm seems that in deno > 1.45 something was added into `test` - pre-check or something - maybe type check
this pre-checks ignore default test pattern - glob {*_,*.,}test.{ts, tsx, mts, js, mjs, jsx} and checks all ts/js files in particular directory
and can fail on non-test files

```
$  deno test --allow-read=__tests__ --allow-write=__tests__ __tests__
Check file:///E:/<fullpath>/__tests__/env-template.ts
Check file:///E:/<fullpath>/__tests__/mockServerLocalConvert_test.ts
Check file:///E:/<fullpath>/__tests__/mockServerLocalResult.js
Check file:///E:/<fullpath>/__tests__/setOptions_test.ts
error: TS2339 [ERROR]: Property 'createEnvConfig' does not exist on type 'Window & typeof globalThis'
```
error is from env-template.ts file  - this is some non-test file - just some data but with .ts extension

in deno  1.44.* no such bad checks are presented and printed and only default pattern matched test files are type checked, executed

**Comment by bartlomieju** [comment]
The behavior itself is intentional: since 1.45 (#24443), any script file inside a `__tests__` directory is treated as a test file, in addition to the `{*_,*.,}test.{ts, tsx, mts, js, mjs, jsx}` glob. The remaining ask here was documentation, which is addressed by denoland/docs#3385, adding the `__tests__` convention to the test file discovery section at https://docs.deno.com/runtime/test/. If a file in such a directory should not be collected as a test, rename the directory or exclude the file via `test.exclude` in the config file.
