### ISSUE TITLE
Error while init prisma using deno 

### ISSUE THREAD

**Issue by harshmangalam** [denoland/deno#18906]
```sh
deno run --allow-read --allow-env --allow-write npm:prisma@^4.5 init
```
✅Granted sys access to "uid".
> Downloading Prisma engines for Node-API for darwin-arm64 [          ] 0%┌ ⚠️  Deno
✅ Granted net access to "binaries.prisma.sh".
> Downloading Prisma engines for Node-API for darwin-arm64 [======== ] 84%error: Uncaught (in promise) TypeError: context.digest is not a function
    at Hash.flush [as _flush] (ext:deno_node/internal/crypto/hash.ts:47:35)
    at Hash.Ot [as _final] (ext:deno_node/_stream.mjs:11:59823)
    at Fa (ext:deno_node/_stream.mjs:11:51130)
    at Ua (ext:deno_node/_stream.mjs:11:51274)
    at mt (ext:deno_node/_stream.mjs:11:51350)
    at Hash.S.end (ext:deno_node/_stream.mjs:11:50523)
    at Gunzip.u (ext:deno_node/_stream.mjs:11:36397)
    at Object.onceWrapper (ext:deno_node/_events.mjs:502:28)
    at Gunzip.emit (ext:deno_node/_events.mjs:391:35)
    at Ea (ext:deno_node/_stream.mjs:11:43461)

```
deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by petamoriken** [comment]
deplicated of #18785, and resolved in Deno v1.33

**Comment by harshmangalam** [comment]
@petamoriken Thanks it works in updated deno version 1.33.1
