### ISSUE TITLE
Since last version of deno compile produce an strange error

### ISSUE THREAD

**Issue by RoXuS** [denoland/deno#12357]
Hey team,

Since the last version of deno, compile cmd produce a strange error:
````
TypeError: Number.isInteger is not a function
    at queue (file://$deno$/bundle.js:4976:17)
    at ProjectResolver.resolveProjects (file://$deno$/bundle.js:7655:31)
    at async Sync.process (file://$deno$/bundle.js:8498:34)
TypeError: Number.isInteger is not a function
TypeError: Number.isInteger is not a function
    at queue (file://$deno$/bundle.js:4976:17)
    at ProjectResolver.resolveProjects (file://$deno$/bundle.js:7655:31)
    at async Sync.process (file://$deno$/bundle.js:8498:34)
````

It works greatly with `deno run`. And compile works on Deno 1.11.2.
I don't have more log than that.
