### ISSUE TITLE
Deno fails to build on FreeBSD 13.0

### ISSUE THREAD

**Issue by dmilith** [denoland/deno#14612]
I've tried building Deno on my FreeBSD boxes with `cargo install deno --version 1.21.3 --locked`, but the build ends (on both arm64 and x86_64) with:

```
   Compiling v8 v0.42.0
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/v8-0.42.0/build.rs:241:18
    |
241 | fn platform() -> &'static str {
    |    --------      ^^^^^^^^^^^^ expected `&str`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression

For more information about this error, try `rustc --explain E0308`.
error: could not compile `v8` due to previous error
```

Used Rust: 1.60.0
System: FreeBSD 13.0-RELEASE

**Comment by AnInternetTroll** [comment]
It's best to build from ports www/deno https://www.freshports.org/www/deno
