### ISSUE TITLE
Root specifiers without a path incorrectly handled.

### ISSUE THREAD

**Issue by grian32** [denoland/deno#9942]
https://github.com/denoland/deno/blob/main/cli/module_graph.rs#L897, only checks for js, sourcemap, not for ts, which means trying to `deno run <link here>` with `<link here>` returning a mimetype of `application/typescript` makes it panic due to unreachable code.

**Comment by somebody1234** [comment]
Don't think that's it - it works for most typescript files, it's just when mimetype is `application/typescript` but typescript doesn't do anything to the file, I'm assuming no files are emitted (i.e. neither a js file nor a sourcemap are emitted)?

**Comment by grian32** [comment]
> please provide a reproduction.

Steps for reproduction:
- run `deno run https://curls.it`
- get error

This happens because the code https://curls.it is sending when the user agent is deno, does not include any typescript features, while the content-type header is `application/typescript`.

The code in question is:
```typescript
console.log(\`\\
hi deno user!
how to use:
go to curls.it
paste file, using 'typescript' (or 'javascript') as file type
copy url
deno run -A <url here>\`);
```

and also available at https://glitch.com/edit/#!/wtmoo?path=tools%2Fcurls.js%3A11%3A2 line 11.

**Comment by ahuggins-nhs** [comment]
It's interesting that faking a "deno" user agent with curl and passing the output on `stdout` works, but that passing the URL directly to deno does _not_.

```shell
curl -s -A "deno" https://curls.it | deno run -
```

**Comment by somebody1234** [comment]
@grian32 btw that code is (double) escaped since it's another template string, might wanna fix that

**Comment by somebody1234** [comment]
Even more oddly, valid ES5 code works fine:
```js
var arr = [12321, 532525, 64364];
for (var i = 0; i < arr.length; i++) {
  console.log(arr[i]);
}
```
It's just something to do with single `console.log`s

**Comment by kitsonk** [comment]
> It's interesting that faking a "deno" user agent with curl and passing the output on stdout works, but that passing the URL directly to deno does not.

Piped content is always treated as JavaScript.

**Comment by kitsonk** [comment]
It shouldn't be going down the code path that it is going down to cause the panic.  It must be a bug elsewhere.  There are some "challenges" with the root modules and how we handle them differently with TypeScript.  It could be that the built in `tsc` isn't actually emitting anything, or emitting something strange for the input code, which could explain it.

**Comment by somebody1234** [comment]
Seems like it's to do with remapping the filenames https://github.com/denoland/deno/blob/f46e39c5c5435696daab9df075482e6e5c83533b/cli/tsc.rs#L432-L435

After remapping, it becomes `https://curls.it/.ts`, i.e. name = `.ts`, ext = none

Can confirm after running a file with name `.ts` through tsc.
```
error TS6054: File '.ts' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
  The file is in the program because:
    Root file specified for compilation


Found 1 error.
```

Not sure what a good way to fix this would be though; you might need to ensure there are no name collisions (?)? (Not sure if this is even a problem if you supply multiple files - if not you could just go with a generic name like `_.ts` or `from_web.ts` or `input.ts` or `script.ts` I guess

**Comment by kitsonk** [comment]
Thanks for narrowing it down, I know what we need to do now, as basically specifiers without a path are not handled properly.

**Comment by bartlomieju** [comment]
Checked on v1.16.4 and this is still a problem.

**Comment by littledivy** [comment]
Works with Deno 1.44.2. Closing.

![image](https://github.com/denoland/deno/assets/34997667/9a823ac0-a132-45d1-8c92-e36b0ef8036a)
