### ISSUE TITLE
Multiple versions of swc_ecma_ast crate when updating deno to 1.1.3 via cargo

### ISSUE THREAD

**Issue by tranzystorek-io** [denoland/deno#6668]
When updating deno to version 1.1.3 with cargo, the build of deno fails with errors such as:

```
error[E0053]: method `visit_import_decl` has an incompatible type for trait
    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.1.3/tsc.rs:1178:3
     |
1178 | /   fn visit_import_decl(
1179 | |     &mut self,
1180 | |     import_decl: &swc_ecma_ast::ImportDecl,
1181 | |     _parent: &dyn Node,
...    |
1188 | |     });
1189 | |   }
     | |___^ expected struct `swc_ecma_ast::module_decl::ImportDecl`, found a different struct `swc_ecma_ast::module_decl::ImportDecl`
     |
     = note: expected fn pointer `fn(&mut tsc::DependencyVisitor, &swc_ecma_ast::module_decl::ImportDecl, &(dyn swc_ecma_visit::Node + 'static))` (struct `swc_ecma_ast::module_decl::ImportDecl`)
                found fn pointer `fn(&mut tsc::DependencyVisitor, &swc_ecma_ast::module_decl::ImportDecl, &(dyn swc_ecma_visit::Node + 'static))` (struct `swc_ecma_ast::module_decl::ImportDecl`)
     = note: perhaps two different versions of crate `swc_ecma_ast` are being used?
```

**Comment by ry** [comment]
I'm confused by this. I can repeat the error, `cargo install deno` fails. It is because there are two versions of swc_ecma_ast in the dependency tree.

I just don't understand why. When I do `git checkout v1.1.3` and I only see one version of swc_ecma_ast:
```
> cargo tree  | grep swc_ecma_ast
│   ├── swc_ecma_ast v0.22.0
│   │   ├── swc_ecma_ast v0.22.0 (*)
│       ├── swc_ecma_ast v0.22.0 (*)
│   ├── swc_ecma_ast v0.22.0 (*)
```

**Comment by tranzystorek-io** [comment]
Looking through `cargo install --verbose deno` logs shows that cargo builds `swc_ecma_ast` versions 0.22.0 and 0.23.0.

Digging deeper, the hash for version 0.23.0 is used in the deps of `dprint-plugin-typescript`. Here something strange happens: the version of dprint-plugin-typescript in cli/Cargo.toml is 0.19.5, while during install cargo picks 0.19.7 😕
