### ISSUE TITLE
How to get types for npm lodash?

### ISSUE THREAD

**Issue by namirsab** [denoland/deno#16994]
## Observed
I'm trying to use lodash from npm. 

I'm doing this import:

```ts
import _ from "npm:lodash@4";
```

This works, and If I log the `_` symbol, I get to see all the underscore functions.

Unfortunately, when I try to call them I get a Typescript error telling me the following:

```js
error: TS2339 [ERROR]: Property 'VERSION' does not exist on type 'typeof import("file:///Users/namirsab/Library/Caches/deno/npm/registry.npmjs.org/lodash/4.17.15/lodash.js")'.
console.log(_.VERSION); // This line causes the error
```

## Expected
I would expect the types to be downloaded together, but I know this is still part of the roadmap.

What can I do though?

## Reproduction

1. Write a file including this

```ts
import _ from "npm:lodash@4";
console.log(_.VERSION);
```

2. Try to run it

Deno version is 1.28.2

**Comment by namirsab** [comment]
After upgrading deno to 1.28.3, it now works, but I'm still not sure how to get types for the npm module and IntelliSense in vscode, but I guess that's a different problem

**Comment by dsherret** [comment]
Lodash ships it's types on definitely typed (that can be figured out by looking at the symbol beside the name here: https://www.npmjs.com/package/lodash). So, to get lodash types working, you need to use a corresponding `@types` package. For example:

```ts
// @deno-types="npm:@types/lodash@4"
import _ from "npm:lodash@4";

console.log(_.VERSION); // works now
```

The initial problem you mentioned was a bug that was fixed in the latest version (as you discovered).

Sorry the docs aren't good on this. I just realized the PR about this hasn't been merged https://github.com/denoland/manual/pull/447
