### ISSUE TITLE
[deno compile] Details: LoadLibraryExW failed

### ISSUE THREAD

**Issue by leonco** [denoland/deno#26095]
Version: Deno 2.0.0
I setup an example prisma project, 
```
deno run -A main.ts
```
works fine, 
```
deno compile -A -o hello.exe ./main.ts
```
also generate a executable file `hello.exe`,

But when i run 
```
./hello.exe
```

an exception thrown:
```
error: Uncaught (in promise) PrismaClientInitializationError: Unable to require(`C:\Users\leo\AppData\Local\Temp\deno-compile-hello.exe\hello-prisma\node_modules\.deno\@prisma+client@5.20.0\node_modules\.prisma\client\query_engine-windows.dll.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: LoadLibraryExW failed
    at Object.loadLibrary (file:///C:/Users/leo/AppData/Local/Temp/deno-compile-hello.exe/hello-prisma/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/runtime/library.js:110:10219)
    at async Ar.loadEngine (file:///C:/Users/leo/AppData/Local/Temp/deno-compile-hello.exe/hello-prisma/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/runtime/library.js:111:448)
    at async Ar.instantiateLibrary (file:///C:/Users/leo/AppData/Local/Temp/deno-compile-hello.exe/hello-prisma/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/runtime/library.js:110:12575)

```

**Comment by petamoriken** [comment]
duplicate of #16642

**Comment by yazan-abdalrahman** [comment]
@leonco 
Can you provide me with the main.ts to try to reproduce the issue?

**Comment by leonco** [comment]
main.ts
```
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient()

```
deno.json

```
{
  "tasks": {
    "dev": "deno run --watch main.ts"
  },
  "imports": {
    "@hono/hono": "jsr:@hono/hono@^4.6.2",
    "@prisma/client": "npm:@prisma/client@^5.20.0",
    "@std/assert": "jsr:@std/assert@1",
    "@std/crypto": "jsr:@std/crypto@^1.0.3",
    "@std/encoding": "jsr:@std/encoding@^1.0.5",
    "prisma": "npm:prisma@^5.20.0",
    "winston": "npm:winston@^3.14.2",
    "winston-daily-rotate-file": "npm:winston-daily-rotate-file@^5.0.0"
  },
  "nodeModulesDir": "auto"
}

```

**Comment by leonco** [comment]
if i use esm import , 
```
import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()
```
an error happed:
```
error: Uncaught SyntaxError: The requested module '@prisma/client' does not provide an export named 'PrismaClient'
import { PrismaClient } from '@prisma/client'

```

**Comment by yazan-abdalrahman** [comment]
@littledivy  @leonco 

I got another error and the same result from both `compile` and `run`, thus I believe it works; it is not a bug. 


**compile:**
```
PS D:\yad\deno\ntlm> $env:DENORT_BIN = "..\target\debug\denort.exe"        
PS D:\yad\deno\ntlm> ..\target\debug\deno compile -A -o hello.exe ./main.ts
Compile file:///D:/yad/deno/ntlm/main.ts to hello.exe
PS D:\yad\deno\ntlm> .\hello.exe
error: Uncaught (in promise) Error: Cannot find module '.prisma/client/default'
Require stack:
- C:\Users\YAZAN~1.ABD\AppData\Local\Temp\deno-compile-hello.exe\ntlm\node_modules\.deno\@prisma+client@5.20.0\node_modules\@prisma\client\default.js
- C:\Users\YAZAN~1.ABD\AppData\Local\Temp\deno-compile-hello.exe\ntlm\main.ts
    at Function.Module._resolveFilename (node:module:859:15)
    at Function.Module._load (node:module:692:27)
    at Module.require (node:module:941:19)
    at require (node:module:1140:16)
    at Object.<anonymous> (file:///C:/Users/YAZAN~1.ABD/AppData/Local/Temp/deno-compile-hello.exe/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:2:6)
    at Object.<anonymous> (file:///C:/Users/YAZAN~1.ABD/AppData/Local/Temp/deno-compile-hello.exe/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:5:4)
    at Module._compile (node:module:1044:34)
    at Object.Module._extensions..js (node:module:1082:10)
    at Module.load (node:module:919:32)
    at Function.Module._load (node:module:738:12)
PS D:\yad\deno\ntlm> 
```

**run:**
```
PS D:\yad\deno\ntlm> ..\target\debug\deno run -A  .\main.ts
error: Uncaught (in promise) Error: Cannot find module '.prisma/client/default'
Require stack:
- D:\yad\deno\ntlm\node_modules\.deno\@prisma+client@5.20.0\node_modules\@prisma\client\default.js
- D:\yad\deno\ntlm\main.ts
    at Function.Module._resolveFilename (node:module:859:15)
    at Function.Module._load (node:module:692:27)
    at Module.require (node:module:941:19)
    at require (node:module:1140:16)
    at Object.<anonymous> (file:///D:/yad/deno/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:2:6)
    at Object.<anonymous> (file:///D:/yad/deno/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:5:4)
    at Module._compile (node:module:1044:34)
    at Object.Module._extensions..js (node:module:1082:10)
    at Module.load (node:module:919:32)
    at Function.Module._load (node:module:738:12)
PS D:\yad\deno\ntlm> 
```

**Comment by yazan-abdalrahman** [comment]
> @littledivy @leonco
> 
> I got another error and the same result from both `compile` and `run`, thus I believe it works; it is not a bug.
> 
> **compile:**
> 
> ```
> PS D:\yad\deno\ntlm> $env:DENORT_BIN = "..\target\debug\denort.exe"        
> PS D:\yad\deno\ntlm> ..\target\debug\deno compile -A -o hello.exe ./main.ts
> Compile file:///D:/yad/deno/ntlm/main.ts to hello.exe
> PS D:\yad\deno\ntlm> .\hello.exe
> error: Uncaught (in promise) Error: Cannot find module '.prisma/client/default'
> Require stack:
> - C:\Users\YAZAN~1.ABD\AppData\Local\Temp\deno-compile-hello.exe\ntlm\node_modules\.deno\@prisma+client@5.20.0\node_modules\@prisma\client\default.js
> - C:\Users\YAZAN~1.ABD\AppData\Local\Temp\deno-compile-hello.exe\ntlm\main.ts
>     at Function.Module._resolveFilename (node:module:859:15)
>     at Function.Module._load (node:module:692:27)
>     at Module.require (node:module:941:19)
>     at require (node:module:1140:16)
>     at Object.<anonymous> (file:///C:/Users/YAZAN~1.ABD/AppData/Local/Temp/deno-compile-hello.exe/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:2:6)
>     at Object.<anonymous> (file:///C:/Users/YAZAN~1.ABD/AppData/Local/Temp/deno-compile-hello.exe/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:5:4)
>     at Module._compile (node:module:1044:34)
>     at Object.Module._extensions..js (node:module:1082:10)
>     at Module.load (node:module:919:32)
>     at Function.Module._load (node:module:738:12)
> PS D:\yad\deno\ntlm> 
> ```
> 
> **run:**
> 
> ```
> PS D:\yad\deno\ntlm> ..\target\debug\deno run -A  .\main.ts
> error: Uncaught (in promise) Error: Cannot find module '.prisma/client/default'
> Require stack:
> - D:\yad\deno\ntlm\node_modules\.deno\@prisma+client@5.20.0\node_modules\@prisma\client\default.js
> - D:\yad\deno\ntlm\main.ts
>     at Function.Module._resolveFilename (node:module:859:15)
>     at Function.Module._load (node:module:692:27)
>     at Module.require (node:module:941:19)
>     at require (node:module:1140:16)
>     at Object.<anonymous> (file:///D:/yad/deno/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:2:6)
>     at Object.<anonymous> (file:///D:/yad/deno/ntlm/node_modules/.deno/@prisma+client@5.20.0/node_modules/@prisma/client/default.js:5:4)
>     at Module._compile (node:module:1044:34)
>     at Object.Module._extensions..js (node:module:1082:10)
>     at Module.load (node:module:919:32)
>     at Function.Module._load (node:module:738:12)
> PS D:\yad\deno\ntlm> 
> ```

I tried ` ..\target\debug\deno add  npm:prisma npm:typescript npm:ts-node npm:@types/node`
, but it still failed `error: Uncaught (in promise) Error: Cannot find module '.prisma/client/default'`. But when I used `npm install prisma typescript ts-node @types/node --save-dev`, I created a project` Prisma`.  this issue disappeared and I got the origin issue, therefore I assume we have an issue with deno `install` and `add`.

**Comment by xxhertz** [comment]
any known temporary solution to this?

**Comment by yazan-abdalrahman** [comment]
> any known temporary solution to this?

```
PS D:\yad\deno\prisma_app> ..\target\debug\deno run  -A .\main.ts                                                                                                                        
PS D:\yad\deno\prisma_app> ..\target\debug\deno compile  -A .\main.ts
Check file:///D:/yad/deno/prisma_app/main.ts
Compile file:///D:/yad/deno/prisma_app/main.ts to prisma_app.exe
PS D:\yad\deno\prisma_app> .\prisma_app.exe
PS D:\yad\deno\prisma_app> ..\target\debug\deno --version                                                                                                                                          
deno 1.45.5 (release, x86_64-pc-windows-msvc)
v8 12.7.224.13
typescript 5.5.2
PS D:\yad\deno\prisma_app> 
```
It works with '`DENO 1.45.5`'. You can downgrade deno using this command: `deno upgrade --version 1.45.5` 
until the primary issue is resolved.

**Comment by andresribeiro** [comment]
even with `deno install --allow-scripts` i still cant use prisma

**Comment by lucacasonato** [comment]
The original report from @leonco is a duplicate of https://github.com/denoland/deno/issues/23266 (`deno compile` does not support native addons yet).

I can not reproduce the `error: Uncaught SyntaxError: The requested module '@prisma/client' does not provide an export named 'PrismaClient'` that @leonco also described. Please provide a full reproduction to get this error (with the commands you are running). I am doing this in a folder with the two files you provided:

```
$ deno install --allow-scripts
$ deno run -A main.ts
```

**Comment by lucacasonato** [comment]
@andresribeiro Please open an issue with reproduction.

**Comment by lucacasonato** [comment]
Closing as the original issue here was a dupe.
