### PR TITLE
Bundles can be sync or async based on top level await

### LINKED ISSUE #4055: [bug] default function in deno bundle is not a function
**v0.34.0**

ERROR:

> error: Uncaught Error: Uncaught TypeError: customFn_js_1.default is not a function
► $deno$/workers.ts:169:17
    at poll ($deno$/workers.ts:169:17)

single function in the .js file to bundle:

```
export default function cubeIt(req, res) {
  const result = 3*3*3;
  res.send({ date: new Date(), result });
}
```

works in **v0.32.0** (System vs AMD for bundling)

@kitsonk the function identifier is no longer "file:///...", but doubt that [change](https://github.com/denoland/deno/pull/4042/files#diff-98b870ba24fef23577c1d2ceedaa0473R309) you have introduced yesterday has anything to do with described behavior, probably the offender is hiding [here](https://github.com/denoland/deno/pull/3965)

### LINKED ISSUE #4123: feat: bundles always use TLA, though browsers don't support TLA
As point out in https://github.com/denoland/deno/issues/4031#issuecomment-590178526 the changes to the bundles to support TLA in TypeScript 3.8 also forced all bundles to require support of TLA, even if none of the modules in the bundle required TLA.  We should fix this since browser support for TLA seems a way off.

### PR DESCRIPTION
**Pull request by kitsonk**
Previously, bundles always utilised top level await, even if the bundled modules didn't require top level await.  This PR performs analysis of the bundle and if none of the bundled modules are asynchronously executed, then the bundle as a whole will be synchronously instantiated.

This does mean though that if a bundled module uses top level await, that will bubble up into the bundle, and currently be incompatible with the browser.  TLA in bundles though won't work until #4100 is merged.

Also this also introduces some minor improvements in the bundle loader which make it even more terse and cryptic in order to save space.

Fixes #4055
Fixes #4123

### CODE REVIEW

**Comment by kitsonk** [comment]
Side note, I also believe that once this is landed, I can refactor `deno_typescript` and the snapshots to use the same bundler code, which seems logical while it might take a while to have ESM modules injected directly into the isolate for snapshotting.

**Comment by kitsonk** [comment]
This is rebase of master which includes 3.8, so this should be ready to go.

**Comment by ry** [comment]
Shouldn't the modules instantiate synchronously?

**Comment by kitsonk** [comment]
> Shouldn't the modules instantiate synchronously?

Not if there is top level await... modules instantiate asynchronously which has to bubble up to a top level await, otherwise you can't support bundling top level await modules.  The was the whole reason to move System from AMD, because AMD will likely never support asynchronous module instantiation, while as System accommodated it.  System aligns to the way the module instantiation happens when there is a TLA in an ESM module and TypeScript emits TLA modules to that standard.
