### ISSUE TITLE
bug: encodeInto implementation is not correct

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9006]
You can enable the failing WPT tests by adding this snippet to `cli/tests/wpt.jsonc`:

```json
{
   "name": "encodeInto",
   "expectFail": [
     // TODO(lucacasonato): enable once we support MessageChannel
     "encodeInto() and a detached output buffer"
   ]
},
```

Errors from the failing tests look like this:
```
encodeInto() into ArrayBuffer with �A�A¥Hi and destination length 10, offset 4, filler random
assert_equals: expected 239 but got 237
Error
    at AssertionError.get_stack (file:///tmp/wpt-bundle-J6kGw.js:3617:21)
    at new AssertionError (file:///tmp/wpt-bundle-J6kGw.js:3610:27)
    at assert (file:///tmp/wpt-bundle-J6kGw.js:3600:19)
    at assert_equals (file:///tmp/wpt-bundle-J6kGw.js:1225:9)
    at Test.<anonymous> (file:///tmp/wpt-bundle-J6kGw.js:4320:13)
    at Test.step (file:///tmp/wpt-bundle-J6kGw.js:2041:25)
    at test (file:///tmp/wpt-bundle-J6kGw.js:569:30)
    at file:///tmp/wpt-bundle-J6kGw.js:4286:7
    at Array.forEach (<anonymous>)
    at file:///tmp/wpt-bundle-J6kGw.js:4285:42
```

**Comment by 00ff0000red** [comment]
I setup a quick test using a detached buffer and Deno threw an exception,
> ```
> error: Uncaught TypeError: Cannot perform %TypedArray%.prototype.entries on a detached ArrayBuffer
>     const iter = value.entries();
> ```

```js
const memory = new WebAssembly.Memory({
	initial: 1,
	maximum: 1,
	shared: false
});

const array = new Uint8Array(memory.buffer, 0, 100);

memory.grow(0);

const result = new TextEncoder().encodeInto("Hello, world!", array);

console.log(array, result);
```

`result` was `{ read: 0, written: 0 }`.

Is this even related to the WPT test assertion?

**Comment by lucacasonato** [comment]
#9143 did not fix the error WPT errors.

**Comment by 00ff0000red** [comment]
Unfortunate. Can I get more details on this WPT test in particular? i.e. its source?

**Comment by lucacasonato** [comment]
Can't you run it? uncomment / comment the tests you care about in //cli/tests/wpt.jsonc, then run `cargo test web_platform_tests`. You can find sources for all the tests in //test_util/wpt.

**Comment by 00ff0000red** [comment]
As far as I can tell, Deno's implementation is okay.

Deno is missing `globalThis.MessageChannel` though, and that is how they detach the buffer.

**Comment by tarruda** [comment]
@lucacasonato is this issue still present? I cannot find `cli/tests/wpt.jsonc`, do you have up-to-date instructions on how I can run this test locally?

**Comment by lucacasonato** [comment]
Yes the issue is still present. The expectations file is now in `tools/wpt/expectations.json`. Instructions for running WPT: https://deno.land/manual@v1.8.3/contributing/web_platform_tests#web-platform-test. If you have more questions feel free to also ask on https://discord.gg/deno :-)

**Comment by tarruda** [comment]
@lucacasonato I've managed to fix the ArrayBuffer failures in #10129. The SharedArrayBuffer tests are still failing though, and doesn't seem to be related to the UTF-8 encoding implementation.

**Comment by tarruda** [comment]
It seems the reason SharedArrayBuffer tests are failing is because the constructor is throwing this:

```
WebAssembly.Memory does not support shared:true
Error: WebAssembly.Memory does not support shared:true
    at file:///tmp/wpt-bundle-d116c909.js:4250:15
    at Test.<anonymous> (file:///tmp/wpt-bundle-d116c909.js:4346:24)
    at Test.step (file:///tmp/wpt-bundle-d116c909.js:2101:25)
    at test (file:///tmp/wpt-bundle-d116c909.js:572:30)
    at file:///tmp/wpt-bundle-d116c909.js:4339:7
    at Array.forEach (<anonymous>)
    at file:///tmp/wpt-bundle-d116c909.js:4338:42
    at Array.forEach (<anonymous>)
    at file:///tmp/wpt-bundle-d116c909.js:4337:5
    at Array.forEach (<anonymous>)
```

**Comment by tarruda** [comment]
The problem is in test_util/wpt/common/sab.js. It uses `new WebAssembly.Memory({ shared:true, initial:0, maximum:0 }).buffer.constructor` as the constructor for SharedArrayBuffer, but throws when it sees that the constructor name is not `SharedArrayBuffer`. Using `SharedArrayBuffer` constructor directly fixes the tests:

```
diff --git a/common/sab.js b/common/sab.js
index d40dd7cca..f1df4f93c 100644
--- a/common/sab.js
+++ b/common/sab.js
@@ -5,10 +5,7 @@ const createBuffer = (() => {
     if (type === "ArrayBuffer") {
       return new ArrayBuffer(length);
     } else if (type === "SharedArrayBuffer") {
-      if (sabConstructor.name !== "SharedArrayBuffer") {
-        throw new Error("WebAssembly.Memory does not support shared:true");
-      }
-      return new sabConstructor(length);
+      return new SharedArrayBuffer(length);
     } else {
       throw new Error("type has to be ArrayBuffer or SharedArrayBuffer");
     }
```

Though I assume the correct fix is in ensuring that `new WebAssembly.Memory({ shared: true })` returns a SharedArrayBuffer.

**Comment by CrimsonCodes0** [comment]
@bartlomieju According to @tarruda, the Wasm shared memory was only one part of the problem here, should this be re-opened?

**Comment by tarruda** [comment]
> the Wasm shared memory was only one part of the problem here

Yes. the failing ArrayBuffer tests were caused by a buggy implementation of encodeInto which is fixed by #10129.

The failing SharedArrayBuffer tests should be fixed by #10116, but some should still fail until #10129 is merged.

**Comment by tarruda** [comment]
I've rebased #10129 to fix some merge conflicts and confirm that most encodeInto tests are fixed. There's still one failure though: " encodeInto() and a detached output buffer". This test requires `MessageChannel` which Deno does not implement yet: #6691
