### ISSUE TITLE
console.log(request) throws in 1.9.2

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#10352]
`echo "console.log(new Request('https://foo'))" | deno run -`

```
error: Uncaught TypeError: this.url is not a function
console.log(new Request('https://foo'))
        ^
    at Request.[Deno.customInspect] (deno:op_crates/fetch/23_request.js:395:19)
    at inspectObject (deno:op_crates/console/02_console.js:925:50)
    at inspectValue (deno:op_crates/console/02_console.js:481:16)
    at inspectArgs (deno:op_crates/console/02_console.js:1454:19)
    at console.log (deno:op_crates/console/02_console.js:1504:9)
```

Found when upgrading from 1.9.0 to 1.9.2

deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2

**Comment by AaronO** [comment]
This is already fixed on `main` via https://github.com/denoland/deno/commit/feb6af77323bfbcb8409ae529c8d152362d1c203 (#10335).

So you can `deno upgrade --canary` to get canary/nightly builds or wait for `1.9.3`

**Comment by ry** [comment]
Oh dang! I thought we had included that fix in 1.9.2 :(
