### ISSUE TITLE
No types for node builtin modules in LSP

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#24401]
Regressed in #24206.

On the previous commit: 
```
deno 1.44.2+3419133 (canary, aarch64-apple-darwin)
```
![Screenshot 2024-07-02 at 2 48 08 PM](https://github.com/denoland/deno/assets/17734409/5da502c7-fa55-4ae0-859e-3f01c08d5e0a)

After PR merged:
```
deno 1.44.2+5dec3fd (canary, aarch64-apple-darwin)
```
![Screenshot 2024-07-02 at 2 47 44 PM](https://github.com/denoland/deno/assets/17734409/75c45a82-781f-4fb2-9bf2-b3cd376a7264)

**Comment by nayeemrmn** [comment]
What's the project configuration / structure?

**Comment by nayeemrmn** [comment]
Also, does it still not work in main / latest canary?

**Comment by Hajime-san** [comment]
Hi, I found a regression that seem to be related  the `npm:` specifier.
Is this related?

Here is an example.

- example.js

```ts
import express from "npm:express@4.19.2";

/** @type {import("npm:@types/express@4.17.21").Express} */
const app = express();
app.use(express.json());
```

# 1.40.4

```bash
% deno -V               
deno 1.40.4
```

And there are no lsp errors.

# 1.44.4

```bash
% mise use deno@latest   
mise ~/.config/mise/config.toml tools: deno@1.44.4
% deno -V                                    
deno 1.44.4
```

And lsp error said as below.

```bash
Property 'use' does not exist on type 'Express'.deno-ts(2339)
```

> [!NOTE]
> There are no errors when `deno check example.js` runs with setting `compilerOptions.checkJs: true` to the config file in both deno versions.

**Comment by nayeemrmn** [comment]
@Hajime-san Please check on `deno upgrade --canary`, that issue should be fixed already.

**Comment by Hajime-san** [comment]
Thanks! It seems to be fixed in canary.
