### ISSUE TITLE
deno fmt broken after upgrade to v0.6.0

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#2382]
```
❯ make
deno fmt ./src/*.ts ./src/**/*.ts
[0/1] Compiling https://deno.land/std/prettier/main.ts/Users/marktiedemann/Library/Caches/deno/deps/https/deno.land/std/prettier/main.ts:183:38 - error TS2339: Property 'path' does not exist on type 'FileInfo'.

183     const parser = selectParser(file.path);
                                         ~~~~
/Users/marktiedemann/Library/Caches/deno/deps/https/deno.land/std/prettier/main.ts:185:34 - error TS2339: Property 'path' does not exist on type 'FileInfo'.

185       checks.push(checkFile(file.path, parser, prettierOpts));
                                     ~~~~
/Users/marktiedemann/Library/Caches/deno/deps/https/deno.land/std/prettier/main.ts:211:38 - error TS2339: Property 'path' does not exist on type 'FileInfo'.

211     const parser = selectParser(file.path);
                                         ~~~~
/Users/marktiedemann/Library/Caches/deno/deps/https/deno.land/std/prettier/main.ts:213:36 - error TS2339: Property 'path' does not exist on type 'FileInfo'.

213       formats.push(formatFile(file.path, parser, prettierOpts));
                                       ~~~~

make: *** [Makefile:10: format] Error 1
```

**Comment by MarkTiedemann** [comment]
Fixed after running the same command with `--reload`. (Never had to do that before after an upgrade.)
