### ISSUE TITLE
TLSSocket._start seems never set

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18303]
**Describe the bug**

https://github.com/denoland/deno_std/blob/bc345306e520e758e8af9b00144c393c9c066c52/node/_tls_wrap.ts#L373

**Steps to Reproduce**

```
import sql from "npm:mssql";

const connectionPool = new sql.ConnectionPool({
  server: "localhost",
  database: "SomeDatabase",
  user: "user",
  password: "password",
  options: {
    trustedConnection: true,
    trustServerCertificate: true,
  },
});

const connection = await connectionPool.connect();
console.log("Connected");
```

**Expected behavior**

Should work.

**Environment**

- OS: Windows 10
- deno version: 1.28.1
- std version: 1.165.0

**Comment by shivajivarma** [comment]
Any update on this?

**Comment by coreybutler** [comment]
This also impacts ldapjs when using an `ldaps://` host.

**Comment by bartlomieju** [comment]
Hey folks, were you able to try the fix available in Deno v1.36.1 for all the packages listed in the issue? I would appreciate some feedback here to know if you encounter any more problems.

**Comment by Niki2k1** [comment]
the [mssql npm library](https://www.npmjs.com/package/mssql) and [nodemailer](https://www.npmjs.com/package/nodemailer) are working now🥳

**Comment by alitavakoli96** [comment]
Hey folks, I'm getting socket hangup error when connecting to azure SQL db I used to get the same error before, but when I upgraded to 1.36.3 from 1.36.1 the issue happening here got fixed but now I'm getting socket hangup error

**Comment by dehrhard** [comment]
Hey hey, unfortunately I'm getting a similar error for nodemailer:
```
 error: Uncaught TypeError: this._socket.removeListener is not a function
     at SMTPConnection._upgradeConnection (file:///home/deno/server/node_modules/.deno/nodemailer@6.9.4/node_modules/nodemailer/lib/smtp-connection/index.js:897:22)
     at file:///home/deno/server/node_modules/.deno/nodemailer@6.9.4/node_modules/nodemailer/lib/smtp-connection/index.js:247:29
     at Object.action (ext:deno_web/02_timers.js:153:11)
     at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
     at eventLoopTick (ext:core/01_core.js:189:21)
```
The offending parts in the code I marked here
![image](https://github.com/denoland/deno/assets/48784121/77303cc7-ce0d-46a9-ba4a-7c0e42862c3f)
Curiously `this._socket.removeListener` is called before `tls.connect` so this must have worked before. I don't understand.

Now I haven't worked on this project for a while so I can't exclude user error but it seems pretty deep in the core code.

**Comment by bartlomieju** [comment]
Thanks for the reports; we'll look into that.

**Comment by bartlomieju** [comment]
@dehrhard could you share the reproduction code for the issue you are encountering?

**Comment by dehrhard** [comment]
@bartlomieju It's pretty much as simple as it gets. Probably it's something stupid.

```
// @deno-types="npm:@types/nodemailer"
import { createTransport, SendMailOptions } from "npm:nodemailer";

const connection = {
  from: "test@test.com",
  host: "host.host.com",
  port: 587,
  auth: {
    user: "123",
    pass: "456",
  },
};

const smtpClient = createTransport({
  connection,
  secure: true,
});

const options: SendMailOptions = {
  from: "test@test.com",
  to: "test1@test.com",
  subject: "Test",
  text: "Content",
  html: "<h1>HTML</h1>",
};
smtpClient.sendMail(options);

```

```
deno run -A main.ts
error: Uncaught TypeError: this._socket.removeListener is not a function
    at SMTPConnection._upgradeConnection (file:///home/x/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:878:22)
    at file:///home/x/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:246:26
    at Object.action (ext:deno_web/02_timers.js:153:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

```
deno --version
deno 1.36.3 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6
```

**Comment by shivajivarma** [comment]
> If it helps, here is another scenario in which this issue can also be seen:
> 
> ```
> import Imap from 'https://esm.sh/imap@0.8.19';
> 
> const imapConfig: Imap.Config = {
>   user: 'redacted',
>   password: 'redacted',
>   host: 'redacted',
>   port: 993,
>   tls: true
> };
> 
> const imap = new Imap(imapConfig);
> 
> imap.once('ready', () => {
>   console.info('ready');
> });
> 
> imap.once('error', (err: Error) => {
>   console.error(err);
> });
>  
> imap.once('end', () => {
>   console.info('Connection ended');
> });
> 
> imap.connect();
> ```
> 
> Error stack trace:
> 
> ```
> ❯ deno run --allow-env index.ts                                                                                                                                                           ─╯
> error: Uncaught TypeError: tlssock._start is not a function
>     tlssock._start();
>             ^
>     at Object.connect (https://deno.land/std@0.153.0/node/_tls_wrap.ts:365:13)
>     at d.connect (https://esm.sh/v96/imap@0.8.19/deno/imap.js:3:1490)
>     at file:///home/ed/code/incoming-email/index.ts:27:6
> ```

This still does not works, it throwing different error now.

**Comment by sant123** [comment]
@shivajivarma what error? Could you post it please?

**Comment by shivajivarma** [comment]
> @shivajivarma what error? Could you post it please?

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rid')
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:226:46)
    at TCP.readStart (ext:deno_node/internal_binding/stream_wrap.ts:96:17)
    at _tryReadStart (node:net:276:30)
    at TLSSocket._read (node:net:856:7)
    at TLSSocket.Readable.read (ext:deno_node/_stream.mjs:2997:16)
    at TLSSocket.read (node:net:789:34)
    at nReadingNextTick (ext:deno_node/_stream.mjs:3326:13)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:30:15)
    at eventLoopTick (ext:core/01_core.js:180:29)
```

**Comment by sant123** [comment]
Perhaps related? https://github.com/denoland/deno/issues/20594

**Comment by vectorkovacspeter** [comment]
> the [mssql npm library](https://www.npmjs.com/package/mssql) and [nodemailer](https://www.npmjs.com/package/nodemailer) are working now🥳 

Do you have sample for this? I still got the same error as the issue creator with latest deno and latest npm sqlserver package 🤔
