### ISSUE TITLE
2.7.1 build failure

### ISSUE THREAD

**Issue by z1atk0** [denoland/deno#32351]
Version: Deno 2.7.1

`deno-2.7.1` won't build for me:

```
$ cargo build
[...]
   Compiling deno_ffi v0.221.0 (/usr/local/src/deno-2.7.1/ext/ffi)
   Compiling libuv-sys-lite v1.48.2
   Compiling test_napi v0.1.0 (/usr/local/src/deno-2.7.1/tests/napi)
   Compiling bencher v0.1.5
   Compiling napi-sys v2.2.2
   Compiling test_server v0.1.0 (/usr/local/src/deno-2.7.1/tests/util/server)
   Compiling node_shim v0.9.0 (/usr/local/src/deno-2.7.1/libs/node_shim)
   Compiling test_ffi v0.1.0 (/usr/local/src/deno-2.7.1/tests/ffi)
   Compiling deno_url v0.222.0 (/usr/local/src/deno-2.7.1/ext/url)
error[E0425]: cannot find type `sockaddr_in` in this scope
   --> /tmp/0-cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libuv-sys-lite-1.48.2/src/functions.rs:785:18
    |
785 |       addr: *mut sockaddr_in,
    |                  ^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:353:1
    |
353 | pub struct sockaddr {
    | ------------------- similarly named struct `sockaddr` defined here

error[E0425]: cannot find type `sockaddr_in6` in this scope
   --> /tmp/0-cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libuv-sys-lite-1.48.2/src/functions.rs:790:18
    |
790 |       addr: *mut sockaddr_in6,
    |                  ^^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:353:1
    |
353 | pub struct sockaddr {
    | ------------------- similarly named struct `sockaddr` defined here

error[E0425]: cannot find type `sockaddr_in` in this scope
   --> /tmp/0-cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libuv-sys-lite-1.48.2/src/functions.rs:793:19
    |
793 |       src: *const sockaddr_in,
    |                   ^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:353:1
    |
353 | pub struct sockaddr {
    | ------------------- similarly named struct `sockaddr` defined here

error[E0425]: cannot find type `sockaddr_in6` in this scope
   --> /tmp/0-cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libuv-sys-lite-1.48.2/src/functions.rs:798:19
    |
798 |       src: *const sockaddr_in6,
    |                   ^^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:353:1
    |
353 | pub struct sockaddr {
    | ------------------- similarly named struct `sockaddr` defined here

error[E0080]: attempt to compute `1_usize - 216_usize`, which would overflow
  --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:77:26
   |
77 |     ["Size of _IO_FILE"][::std::mem::size_of::<_IO_FILE>() - 216usize];
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 56_usize`, which would overflow
   --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:436:26
    |
436 |     ["Size of uv__io_s"][::std::mem::size_of::<uv__io_s>() - 56usize];
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 64_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1124:26
     |
1124 |     ["Size of uv_req_s"][::std::mem::size_of::<uv_req_s>() - 64usize];
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 80_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1134:31
     |
1134 |     ["Size of uv_shutdown_s"][::std::mem::size_of::<uv_shutdown_s>() - 80usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 96_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1144:29
     |
1144 |     ["Size of uv_handle_s"][::std::mem::size_of::<uv_handle_s>() - 96usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 248_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1154:29
     |
1154 |     ["Size of uv_stream_s"][::std::mem::size_of::<uv_stream_s>() - 248usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 192_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1164:28
     |
1164 |     ["Size of uv_write_s"][::std::mem::size_of::<uv_write_s>() - 192usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 248_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1174:26
     |
1174 |     ["Size of uv_tcp_s"][::std::mem::size_of::<uv_tcp_s>() - 248usize];
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 96_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1190:30
     |
1190 |     ["Size of uv_connect_s"][::std::mem::size_of::<uv_connect_s>() - 96usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 216_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1236:26
     |
1236 |     ["Size of uv_udp_s"][::std::mem::size_of::<uv_udp_s>() - 216usize];
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 320_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1246:31
     |
1246 |     ["Size of uv_udp_send_s"][::std::mem::size_of::<uv_udp_send_s>() - 320usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 312_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1256:26
     |
1256 |     ["Size of uv_tty_s"][::std::mem::size_of::<uv_tty_s>() - 312usize];
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 264_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1291:27
     |
1291 |     ["Size of uv_pipe_s"][::std::mem::size_of::<uv_pipe_s>() - 264usize];
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 160_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1301:27
     |
1301 |     ["Size of uv_poll_s"][::std::mem::size_of::<uv_poll_s>() - 160usize];
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 120_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1326:30
     |
1326 |     ["Size of uv_prepare_s"][::std::mem::size_of::<uv_prepare_s>() - 120usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 120_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1336:28
     |
1336 |     ["Size of uv_check_s"][::std::mem::size_of::<uv_check_s>() - 120usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 120_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1346:27
     |
1346 |     ["Size of uv_idle_s"][::std::mem::size_of::<uv_idle_s>() - 120usize];
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 128_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1356:28
     |
1356 |     ["Size of uv_async_s"][::std::mem::size_of::<uv_async_s>() - 128usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 152_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1366:28
     |
1366 |     ["Size of uv_timer_s"][::std::mem::size_of::<uv_timer_s>() - 152usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 160_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1376:34
     |
1376 |     ["Size of uv_getaddrinfo_s"][::std::mem::size_of::<uv_getaddrinfo_s>() - 160usize];
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 1320_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1386:34
     |
1386 |     ["Size of uv_getnameinfo_s"][::std::mem::size_of::<uv_getnameinfo_s>() - 1320usize];
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 136_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1523:30
     |
1523 |     ["Size of uv_process_s"][::std::mem::size_of::<uv_process_s>() - 136usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 128_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1533:27
     |
1533 |     ["Size of uv_work_s"][::std::mem::size_of::<uv_work_s>() - 128usize];
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 56_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1565:31
     |
1565 |     ["Size of uv_cpu_info_s"][::std::mem::size_of::<uv_cpu_info_s>() - 56usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 80_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1575:40
     |
1575 |     ["Size of uv_interface_address_s"][::std::mem::size_of::<uv_interface_address_s>() - 80usize];
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 40_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1586:29
     |
1586 |     ["Size of uv_passwd_s"][::std::mem::size_of::<uv_passwd_s>() - 40usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 24_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1596:28
     |
1596 |     ["Size of uv_group_s"][::std::mem::size_of::<uv_group_s>() - 24usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 1024_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1606:30
     |
1606 |     ["Size of uv_utsname_s"][::std::mem::size_of::<uv_utsname_s>() - 1024usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 88_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1616:29
     |
1616 |     ["Size of uv_statfs_s"][::std::mem::size_of::<uv_statfs_s>() - 88usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 16_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1653:29
     |
1653 |     ["Size of uv_dirent_s"][::std::mem::size_of::<uv_dirent_s>() - 16usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 16_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1728:31
     |
1728 |     ["Size of uv_env_item_s"][::std::mem::size_of::<uv_env_item_s>() - 16usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 128_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1738:30
     |
1738 |     ["Size of uv_metrics_s"][::std::mem::size_of::<uv_metrics_s>() - 128usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 56_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1865:26
     |
1865 |     ["Size of uv_dir_s"][::std::mem::size_of::<uv_dir_s>() - 56usize];
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 440_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1875:25
     |
1875 |     ["Size of uv_fs_s"][::std::mem::size_of::<uv_fs_s>() - 440usize];
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 136_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1894:31
     |
1894 |     ["Size of uv_fs_event_s"][::std::mem::size_of::<uv_fs_event_s>() - 136usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 104_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1904:30
     |
1904 |     ["Size of uv_fs_poll_s"][::std::mem::size_of::<uv_fs_poll_s>() - 104usize];
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 152_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1914:29
     |
1914 |     ["Size of uv_signal_s"][::std::mem::size_of::<uv_signal_s>() - 152usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

   Compiling deno_bench_util v0.228.0 (/usr/local/src/deno-2.7.1/tests/bench_util)
error[E0080]: attempt to compute `1_usize - 144_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1936:29
     |
1936 |     ["Size of uv_random_s"][::std::mem::size_of::<uv_random_s>() - 144usize];
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 312_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:1988:31
     |
1988 |     ["Size of uv_any_handle"][::std::mem::size_of::<uv_any_handle>() - 312usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 1320_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:2033:28
     |
2033 |     ["Size of uv_any_req"][::std::mem::size_of::<uv_any_req>() - 1320usize];
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

error[E0080]: attempt to compute `1_usize - 848_usize`, which would overflow
    --> /usr/local/src/deno-2.7.1/target/debug/build/libuv-sys-lite-77bc3cff7028e018/out/bindings.rs:2057:27
     |
2057 |     ["Size of uv_loop_s"][::std::mem::size_of::<uv_loop_s>() - 848usize];
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `types::_` failed here

Some errors have detailed explanations: E0080, E0425.
For more information about an error, try `rustc --explain E0080`.
error: could not compile `libuv-sys-lite` (lib) due to 45 previous errors
warning: build failed, waiting for other jobs to finish...
```
Here's my build environment:
```
[zlatko@disclosure:~/usrlocal/src]$ lsb_release -d
Description:	Slackware 15.0 x86_64
[zlatko@disclosure:~/usrlocal/src]$ cargo -V
cargo 1.93.1 (083ac5135 2025-12-15) (built from a source tarball)
[zlatko@disclosure:~/usrlocal/src]$ rustc -V
rustc 1.93.1 (01f6ddf75 2026-02-11) (built from a source tarball)
[zlatko@disclosure:~/usrlocal/src]$ bindgen -V
bindgen 0.72.1
[zlatko@disclosure:~/usrlocal/src]$ cbindgen -V
cbindgen 0.29.2
```
`deno-2.6.10` and previous versions would build just fine. If you need any more information, just let me know. Thanks for listening! 🙂 

HAND
Thomas

**Comment by bartlomieju** [comment]
Does it work with Rust 1.92.0? That's the version we use in https://github.com/denoland/deno/blob/main/rust-toolchain.toml

**Comment by z1atk0** [comment]
Hm, I'm using Slackware's packaged version, and they don't keep an archive of older releases. So I'll have to rebuild their `rust` package using 1.92.0 ... no problem, but that's gonna take a while. 😉  I'll report back when I downgraded.

**Comment by Tango992** [comment]
I also get the same error locally and I use Rust 1.92.0. The current workaround is to override the `libuv-sys-lite` version from `=1.48.2` to `=1.48.3`. Maybe we should make a PR for this?

https://github.com/denoland/deno/blob/c585e5f4bee069bbdcc2e25ed4480c8a2cecd3a9/Cargo.toml#L427

**Comment by bartlomieju** [comment]
@Tango992 feel free to bump it then

**Comment by z1atk0** [comment]
Yes, I can confirm that with `libuv-sys-lite = "=1.48.3"` in `Cargo.toml` the build completes fine as usual. 😎  Thanks @Tango992 for figuring that one out, and for preventing me from having to rebuild the `rust-1.92.0` Slackware package on my system! 😉👍
