### ISSUE TITLE
Async Event Handlers are broken in TS files

### ISSUE THREAD

**Issue by dev-nicolaos** [denoland/deno#4220]
### Environment
- Windows 10 Home version 1909
- Deno version 0.35.0

### Steps to Reproduce
1. Create a file `test.ts`
```ts
window.addEventListener("load", async () => {
  console.log("hello");
});
```
2. Run the file: `deno test.ts`

### Expected Behavior
The program prints `hello`, then exits with no errors.

### Actual Behavior
The following error is printed to the console and the program exits without printing `hello`:
```
error TS2345: Argument of type '() => Promise<void>' is not assignable to parameter of type '(event: Event) => void | null'.
  Type 'Promise<void>' is not assignable to type 'void'.

► file:///Path/To/CWD/test.ts:1:33

1 window.addEventListener("load", async () => {
```

### Notes
- I believe having an async function as an event handler is valid JS/TS, it ran in previous versions of Deno (as recently as v30). Thinking it was probably broken by #3899. If I rename the file to `test.js` it runs without a problem.
- I'm guessing this error being thrown has to do with Deno's type declaration for event handlers. While I'm not familiar enough with the code base to know exactly where the problematic declaration is, these seem like likely candidates
  - https://github.com/denoland/deno/blob/a3bfbcceade3d359f677106399562b461b4af01a/cli/js/globals.ts#L107
  - https://github.com/denoland/deno/blob/6cd46fa3ef4b12f35a60f1a33c7f038c06b5fc71/cli/js/lib.deno.shared_globals.d.ts#L45
  - https://github.com/denoland/deno/blob/dd8a10948195f231a6a9eb652e3f208813904ad6/cli/js/event_target.ts#L38
  - https://github.com/denoland/deno/blob/2b0cf74a8f6335ae4e8ef2dfe1010d2695b1c518/cli/js/dom_types.ts#L86

**Comment by kevinkassimo** [comment]
I think marking the return types of callbacks to be `any` might be reasonable here.

I also noticed that `addEventListener` should also be able to take objects implementing [`EventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventListener) interface, not just plain functions.

**Comment by kitsonk** [comment]
We really should follow the [TypeScript typings](https://github.com/microsoft/TypeScript/blob/0326534a2a6c361f5334a66197a3cdd84cb45b6f/lib/lib.webworker.d.ts#L615-L616) for stuff like this as they get a lot of more real world use.  TypeScript has:

```ts
addEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
removeEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
```

**Comment by kevinkassimo** [comment]
@kitsonk I think that is only for `AbortSignal`.

The actual lines we should follow are:
https://github.com/microsoft/TypeScript/blob/0326534a2a6c361f5334a66197a3cdd84cb45b6f/lib/lib.webworker.d.ts#L5667
https://github.com/microsoft/TypeScript/blob/0326534a2a6c361f5334a66197a3cdd84cb45b6f/lib/lib.webworker.d.ts#L1504
