### ISSUE TITLE
deno_crypto v 0.82 fail to compile with rust 1.60 and deno v1.25.2

### ISSUE THREAD

**Issue by reyman** [denoland/deno#16927]
Hi,

I'm trying to package **Deno** for Guix using **rust 1.60**, and actually i encounter these errors with deno crypto :

I use this version v1.25.2 because this is the packaged needed by Quarto software, see configuration into latest release : https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.269

Edit : I also try with rust 1.65, with same error

```

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:187:31
    |
187 |               hash: Some(rsa::hash::Hash::SHA1),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:197:31
    |
197 |               hash: Some(rsa::hash::Hash::SHA2_256),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:207:31
    |
207 |               hash: Some(rsa::hash::Hash::SHA2_384),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:217:31
    |
217 |               hash: Some(rsa::hash::Hash::SHA2_512),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:341:31
    |
341 |               hash: Some(rsa::hash::Hash::SHA1),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:351:31
    |
351 |               hash: Some(rsa::hash::Hash::SHA2_256),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:361:31
    |
361 |               hash: Some(rsa::hash::Hash::SHA2_384),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0433]: failed to resolve: could not find `hash` in `rsa`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:371:31
    |
371 |               hash: Some(rsa::hash::Hash::SHA2_512),
    |                               ^^^^ could not find `hash` in `rsa`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:187:15
    |
187 |               hash: Some(rsa::hash::Hash::SHA1),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:197:15
    |
197 |               hash: Some(rsa::hash::Hash::SHA2_256),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:207:15
    |
207 |               hash: Some(rsa::hash::Hash::SHA2_384),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:217:15
    |
217 |               hash: Some(rsa::hash::Hash::SHA2_512),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:178:21
    |
178 |       let (padding, hashed) = match args
    |                     ^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[u8]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:243:28
    |
243 |             PaddingScheme::new_pss_with_salt::<Sha1, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^         - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:243:13
    |
243 |             PaddingScheme::new_pss_with_salt::<Sha1, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:251:28
    |
251 |             PaddingScheme::new_pss_with_salt::<Sha256, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:251:13
    |
251 |             PaddingScheme::new_pss_with_salt::<Sha256, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:259:28
    |
259 |             PaddingScheme::new_pss_with_salt::<Sha384, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:259:13
    |
259 |             PaddingScheme::new_pss_with_salt::<Sha384, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:267:28
    |
267 |             PaddingScheme::new_pss_with_salt::<Sha512, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:267:13
    |
267 |             PaddingScheme::new_pss_with_salt::<Sha512, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

     Running `CARGO=/gnu/store/6l1pbfzfd5wgyazx4gbsgqgp0p43kn8m-rust-1.60.0-cargo/bin/cargo CARGO_CRATE_NAME=deno_net CARGO_MANIFEST_DIR=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-net-0.60.0.tar.gz CARGO_PKG_AUTHORS='the Deno authors' CARGO_PKG_DESCRIPTION='Networking for Deno' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=deno_net CARGO_PKG_REPOSITORY='https://github.com/denoland/deno' CARGO_PKG_VERSION=0.60.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=60 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps:/gnu/store/zi56fka0w6s7ymm626kjfzz28bgkbapr-rust-1.60.0/lib' rustc --crate-name deno_net --edition=2021 /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-net-0.60.0.tar.gz/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a1d69b6a7ff0a39d -C extra-filename=-a1d69b6a7ff0a39d --out-dir /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps -L dependency=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps --extern deno_core=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libdeno_core-b179b7b620c84a7b.rmeta --extern deno_tls=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libdeno_tls-14796cbbc01f7f1f.rmeta --extern log=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/liblog-62a9d3019a27282c.rmeta --extern serde=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libserde-bff5c0f30046af85.rmeta --extern socket2=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libsocket2-cbabcf05d4c2055c.rmeta --extern tokio=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libtokio-6880427d5cca61c1.rmeta --extern trust_dns_proto=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libtrust_dns_proto-e1141f8928c29427.rmeta --extern trust_dns_resolver=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/deps/libtrust_dns_resolver-579bb673feae9ed9.rmeta --cap-lints warn --cap-lints allow -L native=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/gn_out/obj/ -L native=/tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/target/debug/build/ring-60b157db608f718c/out`
error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:341:15
    |
341 |               hash: Some(rsa::hash::Hash::SHA1),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:351:15
    |
351 |               hash: Some(rsa::hash::Hash::SHA2_256),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:361:15
    |
361 |               hash: Some(rsa::hash::Hash::SHA2_384),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0559]: variant `PaddingScheme::PKCS1v15Sign` has no field named `hash`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:371:15
    |
371 |               hash: Some(rsa::hash::Hash::SHA2_512),
    |               ^^^^ `PaddingScheme::PKCS1v15Sign` does not have this field
    |
    = note: available fields are: `hash_len`, `prefix`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:332:21
    |
332 |       let (padding, hashed) = match args
    |                     ^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[u8]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:398:28
    |
398 |             PaddingScheme::new_pss_with_salt::<Sha1, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^         - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:398:13
    |
398 |             PaddingScheme::new_pss_with_salt::<Sha1, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:406:28
    |
406 |             PaddingScheme::new_pss_with_salt::<Sha256, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:406:13
    |
406 |             PaddingScheme::new_pss_with_salt::<Sha256, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:414:28
    |
414 |             PaddingScheme::new_pss_with_salt::<Sha384, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:414:13
    |
414 |             PaddingScheme::new_pss_with_salt::<Sha384, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^

error[E0107]: this associated function takes 1 generic argument but 2 generic arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:422:28
    |
422 |             PaddingScheme::new_pss_with_salt::<Sha512, _>(rng, salt_len),
    |                            ^^^^^^^^^^^^^^^^^           - help: remove this generic argument
    |                            |
    |                            expected 1 generic argument
    |
note: associated function defined here, with 1 generic parameter: `T`
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-deno-crypto-0.82.0.tar.gz/lib.rs:422:13
    |
422 |             PaddingScheme::new_pss_with_salt::<Sha512, _>(rng, salt_len),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  -------- supplied 2 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-rsa-0.7.0.tar.gz/src/padding.rs:167:12
    |
167 |     pub fn new_pss_with_salt<T: 'static + Digest + DynDigest>(len: usize) -> Self {
    |            ^^^^^^^^^^^^^^^^^


```

**Comment by bartlomieju** [comment]
`deno_crypto` requires `rsa` at fixed version of `0.7.0-pre`, it seems your vendor provides it at `0.7.0`, which is not expected to work.
