### PR TITLE
Support async function and EventListenerObject as listeners

### LINKED ISSUE #4220: Async Event Handlers are broken in TS files
### Environment
- Windows 10 Home version 1909
- Deno version 0.35.0

### Steps to Reproduce
1. Create a file `test.ts`
```ts
window.addEventListener("load", async () => {
  console.log("hello");
});
```
2. Run the file: `deno test.ts`

### Expected Behavior
The program prints `hello`, then exits with no errors.

### Actual Behavior
The following error is printed to the console and the program exits without printing `hello`:
```
error TS2345: Argument of type '() => Promise<void>' is not assignable to parameter of type '(event: Event) => void | null'.
  Type 'Promise<void>' is not assignable to type 'void'.

► file:///Path/To/CWD/test.ts:1:33

1 window.addEventListener("load", async () => {
```

### Notes
- I believe having an async function as an event handler is valid JS/TS, it ran in previous versions of Deno (as recently as v30). Thinking it was probably broken by #3899. If I rename the file to `test.js` it runs without a problem.
- I'm guessing this error being thrown has to do with Deno's type declaration for event handlers. While I'm not familiar enough with the code base to know exactly where the problematic declaration is, these seem like likely candidates
  - https://github.com/denoland/deno/blob/a3bfbcceade3d359f677106399562b461b4af01a/cli/js/globals.ts#L107
  - https://github.com/denoland/deno/blob/6cd46fa3ef4b12f35a60f1a33c7f038c06b5fc71/cli/js/lib.deno.shared_globals.d.ts#L45
  - https://github.com/denoland/deno/blob/dd8a10948195f231a6a9eb652e3f208813904ad6/cli/js/event_target.ts#L38
  - https://github.com/denoland/deno/blob/2b0cf74a8f6335ae4e8ef2dfe1010d2695b1c518/cli/js/dom_types.ts#L86

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #4220

The following are now all valid operations
```ts
window.addEventListener("load", async (e: Event) => console.log('HELLO', e.type));

window.addEventListener("load", {
  handleEvent: (e: Event) => console.log('HELLO2', e.type),
});

window.addEventListener("unload", (e: Event) => console.log('BYE', e.type));

window.addEventListener("unload", {
  handleEvent: async (e: Event) => console.log('BYE2', e.type)
});
```
Output
```
HELLO load
HELLO2 load
BYE unload
BYE2 unload
```

Some references from [TypeScript declaration file](https://github.com/denoland/deno/issues/4220#issuecomment-594159976) and [DOM spec IDL](https://dom.spec.whatwg.org/#interface-eventtarget)

### CODE REVIEW

**Comment by kevinkassimo** [comment]
Requesting review cc @ry @kitsonk
