### ISSUE TITLE
worker close API 

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#3727]
I'm used to close worker via `globalThis.close()` which I've found from [HTML standard](https://html.spec.whatwg.org/multipage/workers.html#dedicatedworkerglobalscope).
And it works in and before 0.29. When I run the code with 0.30, it throws 'globalThis.close is not a function'. I found my `globalThis.close()` actually crash the worker rather than close in earlier version.  I run `console.log(Object.keys(globalThis))` and found the function I need is `globalThis.workerClose()` in Deno, (there is no documentation in deno.land yet).

I propose that it's better to change the API from `workerClose` to `close` to follow the standard.

**Comment by kitsonk** [comment]
I think @bartlomieju is trying to refactor all of it, so that a worker has the right global APIs to match what is expected and nothing more.  It is just going to break a few things along the way until it comes full circle.
