### ISSUE TITLE
Deno add - "Failed to install from package.json" "Unexpected character."

### ISSUE THREAD

**Issue by silverbucket** [denoland/deno#26653]
Version: Deno 2.0.4

```
$ deno add npm:debug
Add npm:debug@4.3.7
error: Failed to install from package.json

Caused by:
    0: Invalid version requirement
    1: Unexpected character.
         ^
         ~
$ cat deno.json
{
  "name": "...",
  "description": "...",
  "version": "3.0.0-alpha.5",
  "exports": "./src/index.ts",
  "tasks": {
    "build": "deno run --allow-read --allow-write scripts/export-json-schema.ts",
    "coverage": "deno coverage | deno run jsr:@silverbucket/threshold 100 88",
    "test": "deno test --coverage --clean --allow-env src/**/*.test.ts"
  },
  "imports": {
    "@silverbucket/threshold": "jsr:@silverbucket/threshold@1.0.2",
    "@types/node": "npm:@types/node@22.5.0",
    "@types/debug": "npm:@types/debug@4.1.12",
    "ajv": "npm:ajv@8.12.0",
    "ajv-formats": "npm:ajv-formats@2.1.1",
    "@silverbucket/ajv-formats-draft2019": "jsr:@silverbucket/ajv-formats-draft2019@1.6.1",
    "debug": "npm:debug@4.3.7"
  }
}
```

**Comment by bartlomieju** [comment]
Do you also have a `package.json` file in your project?

**Comment by bartlomieju** [comment]
I tried reproducing the problem and with provided `deno.json` and running `deno add npm:debug` I don't get any error. @silverbucket could you please provide more information about your project?

**Comment by silverbucket** [comment]
@bartlomieju  Sure what would you like to see? To answer your question, there is no package.json.
```bash
$ ls -al
total 40
drwxr-xr-x@  9 njenning  staff   288 Oct 31 01:26 .
drwxr-xr-x@ 15 njenning  staff   480 Aug 26 23:06 ..
-rw-r--r--@  1 njenning  staff  1077 Aug 26 23:06 LICENSE
-rw-r--r--@  1 njenning  staff   271 Aug 29 14:54 README.md
drwxr-xr-x@  2 njenning  staff    64 Oct 31 01:24 coverage
-rw-r--r--@  1 njenning  staff   823 Oct 31 01:26 deno.json
-rw-r--r--@  1 njenning  staff  5814 Aug 27 17:53 deno.lock
drwxr-xr-x@  4 njenning  staff   128 Aug 27 17:44 scripts
drwxr-xr-x@ 12 njenning  staff   384 Oct 31 01:23 src

$ deno add npm:debug
Add npm:debug@4.3.7
error: Failed to install from package.json

Caused by:
    0: Invalid version requirement
    1: Unexpected character.
         ^
         ~
```

It might be worth mentioning that this is a mono-repo, however I've never had issues converting packages one at a time with deno 1.45, it was only upgrading to 2.0.x that I started getting issues like this.

**Comment by bartlomieju** [comment]
@silverbucket is your reo public so o could try it myself?

**Comment by dsherret** [comment]
We should improve this error message to say the file the error occurs in. Probably there's a package.json in the workspace in this case.

**Comment by silverbucket** [comment]
Using deno `2.0.6` I'm getting another variation of this bug. Same repo I mentioned about, this time it's not with the `package.json` at the root of the repository, but a different pacakge at the same level as the `schemas` package.

```bash
project-root/packages/schemas $ deno install
error: Failed to install '@sockethub/client'
    at file:///project-root/packages/examples/package.json

Caused by:
    0: Invalid version requirement
    1: Unexpected character.
         ^
         ~
```

**Comment by silverbucket** [comment]
@nathanwhit Should I create a new ticket? Or can you re-open this one?

**Comment by nathanwhit** [comment]
Hmm we're putting the dependency in the correct file now, but we error out because we validate all of the `package.json` files in the workspace when we cache the dependencies, and one of them has a version requirement (`workspace:^`) that we don't support.

I feel like maybe we should make `workspace:^` not a hard error? Or at least not a parsing error

**Comment by bartlomieju** [comment]
@nathanwhit we should just support it, see https://github.com/denoland/deno/issues/26726

**Comment by bombillazo** [comment]
Hey, Im facing a similar issue when upgrading from v1.146 to v2.

We have a backend monorepo and it uses `import_map.json` files to manage dependencies per sub module in our monorepo. We don't have a package.json (except our Next.js frontend which is still on node). we do have a deno.jsonc at the root level of our project. After upgrading Deno, we get these errors when we run or try to install:
```sh
# install
error: Error in @stripe/react-stripe-js@3.1.0 parsing version requirement for dependency "react-dom": ">=16.8.0 && <=^19.0.0"
deno install
Caused by:
    0: Invalid version requirement
    1: Unexpected character.
         >=16.8.0 && <=^19.0.0
         ~
```

```sh
# run
Running  service
Watcher Process started.
error: Could not find a matching package for 'npm:pg@8.12.0' in the node_modules directory. Ensure you have all your JSR and npm dependencies listed in your deno.json or package.json, then run `deno install`. Alternatively, turn on auto-install by specifying `"nodeModulesDir": "auto"` in your deno.json file.

Watcher Process started.
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/app/node_modules/type-fest/index.js' imported from 'file:///Users/app/@types/date.types.ts'
    at file:///Users/app/@types/date.types.ts:8:24
```

this is part of our import_map.json file:
```json
{
  "imports": {
    "kysely": "https://esm.sh/kysely@0.27.5",
    "pg": "npm:pg@8.12.0",
    "query-string": "https://esm.sh/query-string@9.1.1?dts",
    "remeda": "https://esm.sh/remeda@2.17.4?dts",
    "stripe": "https://esm.sh/stripe@17.4.0?dts",
    "type-fest": "npm:type-fest@4.30.1",
    "zod": "https://deno.land/x/zod@v3.24.1/mod.ts"
  }
}

```

**Comment by dsherret** [comment]
```
"react-dom": ">=16.8.0 && <=^19.0.0"
```

![image](https://github.com/user-attachments/assets/99a88de3-e38d-4075-87a7-7dea2a954001)

This doesn't work the way they probably think.

```
> import semver from "npm:semver"
undefined
> semver.satisfies("21.0.0", ">=16.8.0 && <=^19.0.0", { loose: true })
true
```

I opened https://github.com/stripe/react-stripe-js/pull/555/files

A huge problem in npm dependencies is npm allows people to just put whatever even when it doesn't make sense. I'll update deno_semver to handle that situation. Follow https://github.com/denoland/deno_semver/issues/41 for updates

I think though the original issue can now be closed because workspace specifiers like `workspace:^` are now implemented https://github.com/denoland/deno/issues/26726
