### ISSUE TITLE
Fails to execute install script with ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by quadratz** [denoland/deno#26742]
I'm encountering an issue when trying to install the `sharp` package. Here’s the relevant configuration and the steps I took:

deno.json:
```json
{
  "nodeModulesDir": "auto",
  "imports": {
    "sharp": "npm:sharp@^0.33.5"
  }
}
```
Cmd:
```sh
deno install --allow-scripts
```
Output:
```log
error: script 'install' in 'sharp@0.33.5' failed with exit code 1
stderr:
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///home/qz/qwik/node_modules/.deno/sharp@0.33.5/node_modules/sharp/install/check' imported from 'file:///home/qz/qwik/node_modules/.deno/sharp@0.33.5/node_modules/sharp'

error: failed to run scripts for packages: sharp@0.33.5
```

#### Steps to reproduce:
1. Run `deno install --allow-scripts` to initialize.
2. Deno throws an error.
3. Run `deno install --allow-scripts` again.
4. This time, no error is thrown.

#### Version:
Deno 2.0.4+770ef14 (canary, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Comment by nathanwhit** [comment]
Regressed in https://github.com/denoland/deno/pull/26558

**Comment by nathanwhit** [comment]
cc @dsherret, it looks like the removal of the special case for CJS entrypoints https://github.com/denoland/deno/blob/4774eab64d5176e997b6431f03f075782321b3d9/cli/worker.rs#L530-L537

broke the case we run a lifecycle script with
```
"install": "node install/check"
```
and translate `node install/check` -> `deno run -A install/check`. Previously we could handle the bare entrypoint, but now we can't.

Not sure if the best fix is to make that work or try to resolve the actual file when we do that node->deno translation (though seems like that could be thorny)

**Comment by dsherret** [comment]
It should be detecting that the module is in an npm package when loading now and then handle cjs that way. We have tests for it, but looks like something broke related to it. I'm working still on cjs stuff so I'll get to this soon.

**Comment by brian-petersen** [comment]
Getting this same error with `npm:protobufjs@7.4.0`. On Deno 2.0.4 I have no issues; on 2.0.5 and 2.0.6 it explodes.
