### ISSUE TITLE
deno publish: Incorrect error for symbol as a property

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#22544]
Version: Deno 1.40.0

```
C:\dev\html>deno publish
Checking fast check type graph for errors...
Ensuring type checks...
Check file:///C:/dev/html/html.ts
error: TS1169 [ERROR]: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
  [rawString]: string;
  ~~~~~~~~~~~
    at file:///C:/dev/html/html.ts:4:18

TS2552 [ERROR]: Cannot find name 'rawString'. Did you mean 'String'?
  [rawString]: string;
   ~~~~~~~~~
    at file:///C:/dev/html/html.ts:5:3

    'String' is declared here.
    declare var String: StringConstructor;
                ~~~~~~
        at asset:///lib.es5.d.ts:544:13

Found 2 errors.

You may have discovered a bug in Deno's fast check implementation. Fast check is still early days and we would appreciate if you log a bug if you believe this is one: https://github.com/denoland/deno/issues/
```

The code is as follows:

```ts
const rawString = Symbol();

/** A string that will not be escaped. */
export interface RawString {
	[rawString]: string;
}

/** Create a raw string that will not be escaped. */
export function raw(str: string): RawString {
	return { [rawString]: str };
}
```

The code works fine, compiles fine, and `deno check` does not detect any errors. Not sure why `deno publish` is not accepting it.

**Comment by dsherret** [comment]
I'd recommend upgrading to 1.41.0. 1.40 is ages ago in `deno publish`'s life.

In this case, the no-slow-types lint rule wasn't properly analyzing interface members with a computed key. I opened https://github.com/denoland/deno_graph/pull/402 to fix it.

For the time being, after upgrading to 1.41.0 you can run `deno publish` with the `--allow-slow-types` flag.

**Comment by MarkTiedemann** [comment]
Oh, sorry, I mistyped, I'm on Deno 1.40.4. That's the latest version which is published on winget... Wish that winget would always have the actual latest Deno version, but that's another issue...

Thank you for your work, @dsherret!

If I publish with `--allow-slow-types` now, can I later republish the same version with fast check? The package I want to publish is done (there will not be any future updates) so I want to avoid publishing two versions.

**Comment by dsherret** [comment]
If you want to ensure it's fast check compatible, it might be best to wait for the next release. Sorry! This will slowly get better over time.

**Comment by MarkTiedemann** [comment]
No worries, it's not urgent, plus I am patient. :) Again, thanks for your work!
