### ISSUE TITLE
Deno task with `cd` commands

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#35622]
Version: Deno 2.9.0

I have the following task to run a npm script in a subfolder:

```
cd _apps/club-search && npm i && npm run build
```

It works fine in Deno 2.8.1. In 2.9.0 I have the following error:

```
vite v7.3.1 building client environment for production...
transforming...
src/main.ts(3,17): error TS2307: Cannot find module './App.vue' or its corresponding type declarations.
ERROR: "type-check" exited with 2.
```

Running the command directly in my terminal works fine, so I guess it's something related with cwd resolution in Deno tasks?

**Comment by dsherret** [comment]
Highly doubt because of `cd`. It probably has something to do with the custom npm command in `deno task`: https://github.com/denoland/deno/blob/4bdf6634c08b4c1e9c98384730dbc172ba3f1777/cli/task_runner.rs#L306

In `deno task` it runs the `npm` commands through Deno sometimes.

**Comment by oscarotero** [comment]
I see. So the task command `npm run build` would execute `deno run build`, so it's Deno who is running the build?
Is there any way to force to run the real `npm`?

**Comment by bartlomieju** [comment]
@oscarotero is your reproduction public?

**Comment by bartlomieju** [comment]
Also, two workarounds at the moment should be possible:
1. `npm run-script build` - the first arg must be exactly run, so run-script skips interception and runs real npm.
2. `npm run build --` - any arg starting with "-" skips interception (the code bails on flags because it doesn't handle
  --workspaces etc.), and npm accepts a trailing --.

**Comment by oscarotero** [comment]
Sorry, it's a private repo, I can't share it.
Thanks for the workaround, I'll try
