### ISSUE TITLE
Unable to import Javascript files from TSX

### ISSUE THREAD

**Issue by actual-size** [denoland/deno#5900]
Minimal reproducible example is:
```
// in mod.tsx
import foo from "./foo.js";
```
Regardless of whether or not foo.js exists, this yields `error: TS2307 [ERROR]: Cannot find module './foo.js' or its corresponding type declarations.`

Behaviour exists when trying to import either `.js` or `.jsx` from `.tsx` and not from any other permutation.

Is this simply a bad error message covering up a case where it expects me to specify a type file?

**Comment by bartlomieju** [comment]
@actual-size thanks for opening the issue; definitely a bug introduced in #5029

**Comment by bartlomieju** [comment]
@actual-size I just tried testing this problem but I'm unable to repeat the problem. Can you provide reproduction that causes this error?

**Comment by actual-size** [comment]
@bartlomieju Just tried the following steps:
```
❯❯❯ echo "import foo from './foo.js'" > testfile.tsx
❯❯❯ deno run testfile.tsx
Compile file:///Users/river/Desktop/testfile.tsx
error: TS2307 [ERROR]: Cannot find module './foo.js' or its corresponding type declarations.
import foo from './foo.js'
                ~~~~~~~~~~
    at file:///Users/river/Desktop/testfile.tsx:1:17
❯❯❯ echo "import foo from './foo.ts'" > testfile.working.tsx     ✘ 1 
❯❯❯ deno run testfile.working.tsx                                                                  ✘ 1 
Compile file:///Users/river/Desktop/testfile.working.tsx
❯❯❯
```

**Comment by actual-size** [comment]
`deno --version` gives me:
```
deno 1.0.1
v8 8.4.300
typescript 3.9.2
```

**Comment by bartlomieju** [comment]
@actual-size can you try with Deno v1.0.2? I fixed some problems related to TSX between 1.0.1 and 1.0.2

**Comment by actual-size** [comment]
Sorry, still happening with v1.0.2

**Comment by apiel** [comment]
I have similar issue: `error: TS2307 [ERROR]: Cannot find module '../jsx' or its corresponding type declarations.
import { node } from '../jsx';`

**Comment by bartlomieju** [comment]
@actual-size thanks, now I can confirm that it's broken. However I tried it with changes from https://github.com/denoland/deno/pull/5817 and it works fine.

**Comment by actual-size** [comment]
Great to hear, thanks for your help!
