### PR TITLE
fix: add stackTraceLimit to ErrorConstructor interface and removed ErrorWithStackTraceLimit interface

### PR DESCRIPTION
**Pull request by JakeChampion**
When upgrading to Deno 2.x from 1.x I noticed that my project began to get the below error from deno-ts:
>Property 'stackTraceLimit' does not exist on type 'ErrorConstructor'.deno-ts(2339)

Looking through the deno codebase I saw that there wasa todo item to add this field, which is why I have opened this pull-request

### CODE REVIEW

**Comment by ry** [comment]
Thanks @JakeChampion !
