### ISSUE TITLE
npm odbc package is not working

### ISSUE THREAD

**Issue by jerebtw** [denoland/deno#19735]
The package https://www.npmjs.com/package/odbc isn't working

```
error: Uncaught Error: Cannot find module '/deno-dir/npm/registry.npmjs.org/odbc/2.4.8/lib/bindings/napi-v6/odbc.node'
Require stack:
- /deno-dir/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js
- /deno-dir/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js
    at Function.Module._resolveFilename (node:module:617:17)
    at Function.Module._load (node:module:497:29)
    at Module.require (node:module:671:23)
    at require (node:module:771:20)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js:6:20)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js:58:4)
    at Module._compile (node:module:718:36)
    at Object.Module._extensions..js (node:module:737:12)
    at Module.load (node:module:652:34)
    at Function.Module._load (node:module:534:16)
```

Example code:
```ts
import odbc from "npm:odbc";

const connection = await odbc.connect("");
await connection.close();
```

https://codesandbox.io/p/sandbox/prod-cdn-zf64wh

**Comment by bartlomieju** [comment]
That's most likely because we don't run `postinstall` script automatically.

**Comment by birkskyum** [comment]
Related to
- #20071

**Comment by bartlomieju** [comment]
This seems to work fine in Deno v2.1.2 `deno run --allow-scripts --unstable-unsafe-proto main.js`.
