### ISSUE TITLE
Vinxi project such as solid-start doesn't work with Deno 2.0

### ISSUE THREAD

**Issue by Ciantic** [denoland/deno#26492]
Deno version: deno --version
deno 2.0.2 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2

Here is a repo: https://github.com/Ciantic/deno-solid-test

This is most likely because Vinxi runs `node.exe` behind the scenes instead of `deno.exe`.

It's notable that *bun* also has the same kind of import errors (e.g. with `bun:sqlite`), but it can be fixed by using a flag `--bun` that fakes bun.exe as node.exe.

Maybe Deno needs similar functionality as `--bun` switch. 

```
11.50.18 [vite] Error when evaluating SSR module C:/Source/JavaScript/solid-start-test/deno-solid-test/src/routes/index.tsx?pick=default&pick=$css: failed to import "jsr:@db/sqlite@0.12"
|- Error: Cannot find module 'jsr:@db/sqlite@0.12' imported from 'C:/Source/JavaScript/solid-start-test/deno-solid-test/src/db/db.ts'
    at nodeImport (C:\Source\JavaScript\solid-start-test\deno-solid-test\node_modules\.deno\vite@5.4.9\node_modules\vite\dist\node\chunks\dep-Cyk9bIUq.js:53036:19)        
    at ssrImport (C:\Source\JavaScript\solid-start-test\deno-solid-test\node_modules\.deno\vite@5.4.9\node_modules\vite\dist\node\chunks\dep-Cyk9bIUq.js:52903:22)
    at undefined
    at async instantiateModule (C:\Source\JavaScript\solid-start-test\deno-solid-test\node_modules\.deno\vite@5.4.9\node_modules\vite\dist\node\chunks\dep-Cyk9bIUq.js:52961:5)
```

[Discord link](https://discord.com/channels/684898665143206084/1298570120653836289)

**Comment by Ciantic** [comment]
Here is same project with Bun for comparison:

https://github.com/Ciantic/bun-solid-project

**Comment by Ciantic** [comment]
I have investigated more, it comes from vite's ESM Module importer in here:

https://github.com/vitejs/vite/blob/main/packages/vite/src/module-runner/esmEvaluator.ts#L32-L38
```
    const initModule = new AsyncFunction(
      ssrModuleExportsKey,
      ssrImportMetaKey,
      ssrImportKey,
      ssrDynamicImportKey,
      ssrExportAllKey,
      // source map should already be inlined by Vite
      '"use strict";' + code,
    )

    await initModule(
      context[ssrModuleExportsKey],
      context[ssrImportMetaKey],
      context[ssrImportKey],
      context[ssrDynamicImportKey],
      context[ssrExportAllKey],
    )
```

Some reason that it works in bun with special imports but not with deno.

**Comment by Ciantic** [comment]
Ahaa! Found the culprit! Vite has whitelisted what are Deno/Bun imports here:

https://github.com/vitejs/vite/blob/fce3b09dcf405072b0e992fc55800e0a58aa88b7/packages/vite/src/node/utils.ts#L91-L98

It is missing **jsr**!

**Comment by Ciantic** [comment]
I made a pull request to support `jsr:` imports in vite:

https://github.com/vitejs/vite/pull/18479

**Comment by fro-profesional** [comment]
Why can't you use the deno official vite plugin for that? https://github.com/denoland/deno-vite-plugin

**Comment by fro-profesional** [comment]
> Why can't you use the deno official vite plugin for that? https://github.com/denoland/deno-vite-plugin

Never mind, I tried and it did resolve the imports but got a different error, I'll create a repro for that and create and issue with deno/vinxi unsure where the issue is, but jsr resolver is working

**Comment by Ciantic** [comment]
I'm starting to think this is not possible, because `jsr:` imports are not possible in Deno's node compatibility mode. 

With pure deno mode I have test repo:

https://github.com/Ciantic/deno-pure-solid-start

But it yields even more weirder errors:

```
[h3] [unhandled] Error: Failed to load url ./src/database.ts (resolved id: ./src/database.ts) in deno::TypeScript::@db/sqlite::C:/Users/jarip/AppData/Local/deno/remote/https/jsr.io/ff2127150c5fc24dbc6b1daba62c248f566cce7c9346539da1003b4019d972c2. Does the file exist?
```

**Comment by thesmartwon** [comment]
Duplicate of #23929.

**Comment by bartlomieju** [comment]
This is resolved by the official [`@deno/vite-plugin`](https://github.com/denoland/deno-vite-plugin), which routes module resolution through Deno's own loader instead of relying on Vite's built-in specifier whitelist.

`jsr:` specifiers are explicitly supported: they are listed in the plugin README (alongside `npm:`, `http(s):`, and `deno.json` aliases), there is a test fixture importing `jsr:@std/path`, and the resolver handles `jsr:`/`http(s):` URLs directly.

Usage:

```
deno install npm:@deno/vite-plugin
```

```ts
import deno from "@deno/vite-plugin";

export default defineConfig({
  plugins: [deno()],
});
```

The original failure was Vite-side (its SSR `isBuiltin` whitelist did not include `jsr:`), so the plugin is the correct fix. Closing as resolved. See also #23929.
