### ISSUE TITLE
Node compatibility: Global `performance` object doesn't have `markResourceTiming` function

### ISSUE THREAD

**Issue by trustytrojan** [denoland/deno#29539]
Version: Deno 2.3.5

FYI this error **only occurred after I upgraded from 2.3.1 to 2.3.5.**

Here's a stacktrace, I'm trying to use `npm:discord.js-selfbot-v13` which depends on `npm:undici@6.21.3`:
```
error: Uncaught TypeError: markResourceTiming is not a function
    at finalizeAndReportTiming (file:///home/t/Projects/autobump/node_modules/.deno/undici@6.21.3/node_modules/undici/lib/web/fetch/index.js:308:3)
    at Object.handleFetchDone [as processResponseEndOfBody] (file:///home/t/Projects/autobump/node_modules/.deno/undici@6.21.3/node_modules/undici/lib/web/fetch/index.js:124:3)
    at file:///home/t/Projects/autobump/node_modules/.deno/undici@6.21.3/node_modules/undici/lib/web/fetch/index.js:1059:42
    at ext:core/01_core.js:294:9
    at Object.runMicrotasks (ext:core/01_core.js:692:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:185:21)
```

And here is a snippet of the `npm:undici@6.21.3` code in question:
![Image](https://github.com/user-attachments/assets/ebe08f40-c1bb-4d79-9ddc-568e1e913c4e)

Unfortunately I'll have to use Node.js to run this service for the time being, hope this gets fixed in the next hotfix release
