### PR TITLE
fix: compilation error introduced by #4543

### PR DESCRIPTION
**Pull request by uki00a**
#4543

### CODE REVIEW

**Comment by bartlomieju** [comment]
@uki00a it looks like CI failure is not related to your change, try resetting the CI by pushing an empty commit `git commit --allow-empty -m "reset CI"`

File: std/io/bufio_test.ts [hunk 1]
```diff
@@ -447,21 +447,24 @@ Deno.test("readStringDelimAndLines", async function (): Promise<void> {
...
-  assertNotEOF(r2);
-  assertEquals(decoder.decode(r2.line), "z");
-  assert(
-    r1.line.buffer !== r2.line.buffer,
-    "array buffer should not be shared across reads"
-  );
-});
+Deno.test(
+  "bufReaderShouldNotShareArrayBufferAcrossReads",
+  async function (): Promise<void> {
```
Comment (ry) [inline std/io/bufio_test.ts:452]: we should use arrow syntax when providing a function as a parameter

Comment (bartlomieju) [reply std/io/bufio_test.ts:452]: This syntax is not enforced at the moment anyway and there's plenty of tests using `async function (): Promise<void>`.
