### ISSUE TITLE
std@0.177.0/node/http.ts fails on 1.34.0

### ISSUE THREAD

**Issue by ije** [denoland/deno#19259]
error log:

```
error: TypeError: DenoServe(...).then is not a function
    ).then(() => this.#servePromise!.resolve());
      ^
    at ServerImpl.#serve (https://deno.land/std@0.177.0/node/http.ts:654:7)
    at https://deno.land/std@0.177.0/node/http.ts:561:33
    at Array.processTicksAndRejections (https://deno.land/std@0.177.0/node/_next_tick.ts:33:11)
```

Deno 1.33 works correctly.

**Comment by bartlomieju** [comment]
Would it help esm.sh if I released 0.177.1 that specifically works with HTTP server in Deno V1.34?

**Comment by ije** [comment]
> Would it help esm.sh if I released 0.177.1 that specifically works with HTTP server in Deno V1.34?

yes!!! thanks

**Comment by bartlomieju** [comment]
@ije I opened https://github.com/denoland/deno_std/pull/3406 could you test locally and tell me if that works for you?

**Comment by ije** [comment]
thank you @bartlomieju,  another error throws after upgrade to 0.177.1

```
error: Module not found "https://deno.land/std@0.177.1/node/crypto.ts".
    at http://localhost:8080/v124/cookie-signature@1.0.6/deno/cookie-signature.mjs:2:18
```

**Comment by bartlomieju** [comment]
@ije I pushed the tag, it should work now. Please try it again and let me know.

**Comment by ije** [comment]
yesssss, works for me now! thank you @bartlomieju
